### ISSUE TITLE
NT-Scenario View-Reports

### ISSUE THREAD

**Issue by patrickomni** [patrickomni/omnimobileserver#10]
1. Signin as no credentials
2. Select Account to Impersonate as Reisner Distributor, Inc / Reisner Client Should the words be "Lastest Report" OR "Latest" Report

![image](https://cloud.githubusercontent.com/assets/12114620/7519300/ceea9d48-f4fd-11e4-9597-06ddd0e37fc1.png)

**Comment by christopherdude** [comment]
Good catch.  Someone double-clicked it, and changed it by typing in a typo.  I have double-clicked it and changed it to spell correctly.

**Comment by CaseyDengler** [comment]
Looks good now.
