### ISSUE TITLE
Sempra Scenario View (Traps View) Shows Temperature

### ISSUE THREAD

**Issue by danomni** [patrickomni/omnimobileserver#103]
In the 'Checking Change' table, 'Temp
![screen shot 2015-05-22 at 11 13 09 am](https://cloud.githubusercontent.com/assets/10458099/7776901/90afafb0-0073-11e5-9da9-83301b9cb6d3.jpg)
' is displayed as a column. This should be eliminated

**Comment by patrickomni** [comment]
Fixed
