### ISSUE TITLE
Decimel Place For 'Battery (V)' is Missing

### ISSUE THREAD

**Issue by danomni** [patrickomni/omnimobileserver#104]
In the 'Checking Change' table there is no decimel place for voltage. Ex: In screenshot the first row battery level should read 2.9 and so on

![screen shot 2015-05-22 at 11 13 51 am](https://cloud.githubusercontent.com/assets/10458099/7776942/e1271b36-0073-11e5-8a9b-f13d498fbdc1.jpg)

**Comment by patrickomni** [comment]
It does, now, but only if it needs one (ie. 3   or 3.1).

These won't show up in the sempra data until new data comes in

**Comment by davroth** [comment]
Close?

**Comment by davroth** [comment]
Fixed
