### ISSUE TITLE
Clicking outside the rules box automatically closes it

### ISSUE THREAD

**Issue by CaseyDengler** [patrickomni/omnimobileserver#107]
Steps:
1) Log into Omni
2) Go to any user with changeable rules
3) Click outside of the rules box

Occurs:
The page automatically closes and no rules that were made are saved

Expected:
Hard to say. On one hand, clicking outside of boxes such as these are a common way to get out of them, yet as issue #69 pointed out, moving the mouse outside of the box when releasing the mouse click can cause the same effect, which is unexpected.

**Comment by christopherdude** [comment]
Fixed
