### ISSUE TITLE
Site Freezes when going into a subcategory in Chrome

### ISSUE THREAD

**Issue by CaseyDengler** [patrickomni/omnimobileserver#108]
Steps:
1) Log into Omni using Chrome
2) Go to Traps, Tanks, or Fridge
3) Select a subcategory from the drop down menu on the top left (Boat 2 for example)

Occurs:
The site does load up the page, but it's all grey and nothing can be interacted with.
Even after refreshing, this bug shows up again and again.
![grey site](https://cloud.githubusercontent.com/assets/12438510/7780314/e348df8a-0091-11e5-8ace-9273ca072def.png)

Note: I don't know if I was able to get to these categories before this bug came up, but it shows up every time in Chrome now.

**Comment by CaseyDengler** [comment]
Also freezes on iPad safari according to issue #133

**Comment by davroth** [comment]
fix in V1

**Comment by christopherdude** [comment]
Fixed!  Check changeset 705

**Comment by davroth** [comment]
No repro using Chrome v43, Windows 8.1
