### ISSUE TITLE
Hitting Save in the Users tab of an account creates an additional account for each user in the list

### ISSUE THREAD

**Issue by patrickomni** [patrickomni/omnimobileserver#12]
1. Log into Omni
2. Create a new account
3. Add a user to the account
4. Hit 'Save user'
5. Add a new user to the account
6. Hit 'Save user'
7. Hit 'Save' in the user tab

Occurs:

A user is added to the existing account and a new account by the same name, but with the new user's name at the end, is created. Both accounts have identical information inside of them.

**Comment by christopherdude** [comment]
This is assigned back to Patrick b/c the create new account doesn't return to me an account.  There is a bug assigned to him for this.  Once this is fixed, please re-assign this bug back to me.

**Comment by patrickomni** [comment]
Does now : )

**Comment by patrickomni** [comment]
Fixed
