### ISSUE TITLE
Sempra Scenario View - no graph pane on carousel

### ISSUE THREAD

**Issue by davroth** [patrickomni/omnimobileserver#123]
IE 11 on Windows 8.1 - the carousel cannot be advanced to display a graph. I'm not sure whether this is a data issue or some other problem

Steps:
1. Log on anonymously to http://omnistaging.azurewebsites.net and select Sempra / Marie Van Zandt
2. Observe page that is displayed 
3. Click icon to advance icon

Expected - graph view

Actual - nothing happens

**Comment by CaseyDengler** [comment]
There is no other data, as traps don't have any graphs, so there is nothing to advance to. Though this does bring up an issue where it seems like the user can switch displays when there are no others. I'll close this issue and make a new one addressing it.
