### ISSUE TITLE
Switching between different data sheets (graph and map for example) appear to be possible when they are not

### ISSUE THREAD

**Issue by CaseyDengler** [patrickomni/omnimobileserver#125]
Steps:
1) Log into Omni
2) Go to Traps
3) Observe the left and right arrows below the map

Occurs:
These two arrows bring an assumption to the user that there is more information and when clicking on these arrows does nothing, confusion occurs.
![confusing arrows](https://cloud.githubusercontent.com/assets/12438510/7872532/a210b644-054d-11e5-9478-9cf473835f4b.png)

Expected:
There should be no arrows present when there is nothing to turn to.

**Comment by patrickomni** [comment]
This is a duplicate. Find it and close this one.

**Comment by CaseyDengler** [comment]
Duplicate of Issue #86
