### ISSUE TITLE
When there is no new data, the graph does not fill in the gap of information until new information is given

### ISSUE THREAD

**Issue by CaseyDengler** [patrickomni/omnimobileserver#126]
To reproduce you might have to artificially recreate the data. If needed, simply make it so there's no data for a few days.
For now, it seems that this error can be seen normally
Steps:
1) Log into Omni
2) Go to Fridge
3) Select "30 Days" for the graph

For reference, this information was observed at 5/28/2015 at around 3:50pm.

Expected:
Given that it's been a few days since new information has been sent, the graph should show that by having a large blank space in front of the last information.

Occurs:
Rather than show the gap in time, the graph simply pretends that the last time data was given is what the end of the graph should be. If someone is not paying attention to the exact date, then they could be unaware of the missing information.

![graph missing info](https://cloud.githubusercontent.com/assets/12438510/7873002/f6994704-0551-11e5-978a-73f362be8c62.png)

**Comment by patrickomni** [comment]
By design.

**Comment by CaseyDengler** [comment]
Odd design, could cause issues. Should discuss later.

**Comment by davroth** [comment]
related to #238
