### ISSUE TITLE
Graph and Table work off of two different clock set ups (12hr and 24hr)

### ISSUE THREAD

**Issue by CaseyDengler** [patrickomni/omnimobileserver#127]
Steps:
1) Log into Omni
2) Go to Tanks
3) Select "3 Days" from the drop down box for the graph
4) Hover over a section of the graph between 1:00pm and 12:00am
5) Observe data table on the left side of the page, specifically the "Time" section

Occurs:
The graph seems to work off of a 24 hour based clock, that is, once the time is 1:00pm, the graph will say that its 13:00. The table on the other hand will use the more common 12:00 clock with am and pm, causing some confusion an inconsistency between the two.
![inconsistent clock settings](https://cloud.githubusercontent.com/assets/12438510/7873150/5df77122-0553-11e5-8886-56c6f84fe923.png)

Expected:
Either both the graph and the table use the 12 or 24 hour clock, or the user is able to decide what kind of clock to use (don't know if the user should be able to change them separately).

**Comment by patrickomni** [comment]
default to 12 hour for now

**Comment by christopherdude** [comment]
Put in an entirely new JS function called getClockTime(x) which takes a dateTime and converts it to the correct time.

**Comment by davroth** [comment]
fixed
