### ISSUE TITLE
Save button not showing any confirmation.

### ISSUE THREAD

**Issue by patrickomni** [patrickomni/omnimobileserver#13]
Signin without credentials, Add new account, then add new user with account name and scenario type and click on save button it will create user but not show any message or popup alert that user is created or not for confirmation. Due to which confusion occurs and if user again click the save button then it will create multiple user account with same name.

**Comment by christopherdude** [comment]
This is pending a fix on Pat's part where the account is not returning the account created.  Pat, re-assign this bug to me once this is fixed.

**Comment by patrickomni** [comment]
Fixed
