### ISSUE TITLE
Graph does not default to the 24 hour section after saving rules

### ISSUE THREAD

**Issue by CaseyDengler** [patrickomni/omnimobileserver#130]
Steps:
1) Log into Omni
2) Go to Fridge
3) Select the "30 days" section from the drop down box for the graph
4) Open up the rules section
5) Click "Save rules"
6) Observe the graph again

Occurs:
The drop down box claims that the graph is representing the last 24 hours, but the graph is actually showing the information from "30 days" still.
![inconsistent graph after saving](https://cloud.githubusercontent.com/assets/12438510/7873458/8ea5e8fe-0557-11e5-934a-51d41ecf1e2c.png)

Expected:
Either the graph is defaulted to 24 hours along with the drop down box, or the drop down box stays consistent with the graph.

**Comment by christopherdude** [comment]
Fixed... hopefully didn't screw something else up.  If so, the change was in LoadPage() method in JS, $("#cboItemDetailsNumberOfDays").val(numberOfDays);

**Comment by CaseyDengler** [comment]
Looks good
