### ISSUE TITLE
Unable to scroll through the page after saving rules

### ISSUE THREAD

**Issue by CaseyDengler** [patrickomni/omnimobileserver#131]
Steps to reproduce:
1) Log into Omni
2) Go to Traps
3) Open up the rules window
4) Click on "Save rules"
5) Attempt to scroll down the page

Expected:
User is able to scroll though the page normally

Occurs:
The page refuses to let the user scroll through the page (unless the user clicks and hold down the middle mouse button and moves the mouse up or down).

**Comment by patrickomni** [comment]
For now, add scroll bars to the list of devices.

**Comment by christopherdude** [comment]
This is a really, really, really ugly bug.  It's going back to the Google Maps API loading issue.  I've spent a lot of time in InitializeMap(), LoadAfterGoogleLoaded(), and RefreshMapAsNeeded() javascript methods trying to nail this down.  I'm 98% sure this is a Google maps reload issue.  In the interest of getting other bugs resolved, I'm going to move on from this one and come back.

**Comment by davroth** [comment]
Fix in V1; site needs to work for Sempra, and they will require scrolling

**Comment by christopherdude** [comment]
I believe I have fixed this - CROSSING FINGERS

**Comment by davroth** [comment]
No repro on Chrome v43 and IE 11, Windows 8.1
