### ISSUE TITLE
Test Tanks has no devices

### ISSUE THREAD

**Issue by CaseyDengler** [patrickomni/omnimobileserver#135]
Steps:
1) Log into Omni
2) Go to "Test Tanks"

Occurs:
The page is bare of any information related to devices. The user is also unable to interact with the page itself.
![no devices](https://cloud.githubusercontent.com/assets/12438510/7895550/c44113ce-0649-11e5-995c-1429d3be9e6f.png)

**Comment by patrickomni** [comment]
this is true

**Comment by patrickomni** [comment]
AHA!!!!! The device was there, but the tank was not :)
