### ISSUE TITLE
Simulations don't appear to be working for Test Fridge and Traps

### ISSUE THREAD

**Issue by CaseyDengler** [patrickomni/omnimobileserver#136]
Steps:
1) Log into Omni
2) Impersonate Test Fridge
3) Click on the rules for an individual device
4) Add your number to the Additional Phone Numbers list
5) Click on Save Rules
6) Open rules back up
7) Simulate High Temperatures
8) Save Rules again
9) Observe data table and graph

Neither the graph nor the table show any change. No information is put on the graph and the table always says that the temperature for Fridge 1 is 9 and Fridge 2 is 7, no matter what.
![no information](https://cloud.githubusercontent.com/assets/12438510/7895576/4ace3ab0-064b-11e5-8a07-19112c374d10.png)

**Comment by patrickomni** [comment]
Casey please validate my fix

**Comment by davroth** [comment]
Related to #132 - move to next iteration and determine whether we even want simulation msgs to display on graph

**Comment by CaseyDenglerOmni** [comment]
During the last test pass I never encountered this bug, so I'm closing it.
