### ISSUE TITLE
Save User not working some times

### ISSUE THREAD

**Issue by patrickomni** [patrickomni/omnimobileserver#14]
1. Signin without credentials
2. Add new account or edit existing account
3. Go to the Users tab
4. Fill in all boxes for a new user
5. Click on "Save User"

Expected:
The new user is saved into the system and a new user many be added if desired

Occurred:
The "Save User" button does not work, and nothing changes when clicking on it or the "Save" button. The information entered is still filled in the boxes though.

**Comment by patrickomni** [comment]
Assigning to Casey to get more accurate steps to reproduce.

**Comment by CaseyDengler** [comment]
Gave some more information. Also, it seems like users are refusing to be be added all together.

**Comment by CaseyDengler** [comment]
Nothing new so far, but the first attempt that I made on saving a new user on an account with no other users resulted in the background of the site going dark (as if trying to load something). The user was never saved though, and now any attempts to add new users results in the problems shown in #25

**Comment by christopherdude** [comment]
We may have this fixed.

**Comment by patrickomni** [comment]
Fixed
