### ISSUE TITLE
Staging site - anonymous login hangs

### ISSUE THREAD

**Issue by davroth** [patrickomni/omnimobileserver#140]
Not sure if anonymous logins have been disabled, but the user experience results in a hung system:
1. After having logged out of NetTelligence, browse to http://omnistaging.azurewebsites.net using IE 11 on Windows 8.1
2. Login dialog is displayed
3. Click "Sign-in" button w/ entering username/password

Expected - either login and display all accounts available OR fail w/ "Unknown username/password" error message

Actual - system hangs 
![capture - login hang](https://cloud.githubusercontent.com/assets/12534533/7942538/ab9c4a9c-0913-11e5-8066-cf6689555885.PNG)

**Comment by patrickomni** [comment]
fixed

**Comment by CaseyDengler** [comment]
Sort of fixed.
The site doesn't hang anymore, but the user is brought to an nearly black page aside from the frame work for devices and graphs.
![no sign in blank page](https://cloud.githubusercontent.com/assets/12438510/7947402/c12813be-0931-11e5-9ca0-2ea9a069c441.png)

The user should either be given a list of users to impersonate or edit (from before for testing), or the site just says that it's in invalid log in (much like on chrome).

**Comment by patrickomni** [comment]
This is because there was a user of name blank name and blank password.  Let's stop adding these until we fix the over all.
