### ISSUE TITLE
Newly created account - can't edit region labels

### ISSUE THREAD

**Issue by davroth** [patrickomni/omnimobileserver#143]
1, Browse to http://omnistaging.azurewebsites.net/emp and click "add new account"
2. Add account and user
3. Return to http://omnistaging.azurewebsites.net/emp and click on the newly created account
4. Dashboard is displayed

Expected - able to click on "region" labels (e.g., "Checking Change") to change the label

Actual - can't do that

**Comment by patrickomni** [comment]
check with and without Dave's login

**Comment by davroth** [comment]
Still can't edit labels on Samba. Tried creating another Test Account (in Refrigeration again) and got same failure. Picture below shows single word highlighted after doubleclicking

![Uploading Capture - label edit.PNG…]()

**Comment by davroth** [comment]
![capture - label edit](https://cloud.githubusercontent.com/assets/12534533/7964712/1e968ed0-09ce-11e5-820f-9500475d22f2.PNG)

**Comment by patrickomni** [comment]
Cannot repro this Casey can you try

**Comment by CaseyDengler** [comment]
Also cannot reproduce. Used IE 11 and Chrome version 43.0.2357.81. Were you using anything different Dave?

**Comment by davroth** [comment]
hmmm - using IE 11 and it's working now; closing bug
