### ISSUE TITLE
Test Tanks graph key has both devices labeled as "Tank 1"

### ISSUE THREAD

**Issue by CaseyDengler** [patrickomni/omnimobileserver#147]
Steps:
1) Log into Omni
2) Impersonate "Test Tanks"
3) Observe the graph

Occurs:
The graph seems to believe that both devices are labeled as "Tank 1"
![test tanks graph miss named key](https://cloud.githubusercontent.com/assets/12438510/7950296/47640eae-094d-11e5-9379-b33ef869624f.png)

Expected:
The key refers to Tank 1 and Tank 2 respectively.

**Comment by patrickomni** [comment]
![image](https://cloud.githubusercontent.com/assets/12114620/7975300/bb225344-0a21-11e5-9673-eca13dea3a11.png)

hopefully fixed this time
