### ISSUE TITLE
Graph keys disappear when saving rules

### ISSUE THREAD

**Issue by CaseyDengler** [patrickomni/omnimobileserver#148]
Steps:
1) Log into Omni
2) Impersonate "Test Fridge"
3) Open up the site rules
4) Click on "Save rules"
5) Observe graph

Occurs:
The key for the graph seems to disappear
![test fridge graph miss named key](https://cloud.githubusercontent.com/assets/12438510/7950341/2d2c6850-094e-11e5-85f1-c57a56c0b7eb.png)

Expected:
Key stays intact

**Comment by christopherdude** [comment]
This was an excellent catch.  I've re-done the JS to accommodate now.  'Twas a little difficult to nail down.

**Comment by davroth** [comment]
fixed - could not repro w/ IE 11, Windows 8.1 when testing w/ Reisner and Omni Refrigeration
