### ISSUE TITLE
Label edit - bubble text reports success even when no change has been made

### ISSUE THREAD

**Issue by davroth** [patrickomni/omnimobileserver#149]
1. Browse to http://nettelx.azurewebsites.net/login and log in using Patrick's account
2. Select Sempra account 
3. Double click label to bring up edit box
4. Exit edit box without making any changes

Actual: bubble saying resource has been successfully changed

Expected: bubble saying "no change has been made"

Not a high priority, but part of fit/finish

**Comment by christopherdude** [comment]
This was by design.  This was the desired result.  I had it before so that the user had to hit ENTER to save it, but it was desired to save even when the user went away from it with no change.
