### ISSUE TITLE
NT- Employee - Omni Refrigeration/ Fridge Sample /Graph

### ISSUE THREAD

**Issue by patrickomni** [patrickomni/omnimobileserver#15]
Signin without credentials, select Omni Refrigeration/Fridge Sample and unchecked the device then graph detail will disappear from the website but if user will do Zoom in , Zoom Out then graph details will appear in the website.

Steps to reproduce:
1. Select Omni Refrigeration/Fridge Sample and unchecked the devices
2. Do Zoom in , Zoom Out in the website and analyse the graph.

Before Zoom In

![fridgesampler](https://cloud.githubusercontent.com/assets/12114620/7538008/9e17c228-f5ba-11e4-955c-e323ee5bad10.png)

After Zoom Out

![fridgezoom](https://cloud.githubusercontent.com/assets/12114620/7538018/bdd9fc0c-f5ba-11e4-8394-c64480156131.png)

**Comment by christopherdude** [comment]
Fixed

**Comment by CaseyDengler** [comment]
Can't find the problem, closing.
