### ISSUE TITLE
Recent alerts table disappears after refreshing Test Traps

### ISSUE THREAD

**Issue by CaseyDengler** [patrickomni/omnimobileserver#151]
Steps to reproduce:
1) Log into Omni
2) Impersonate Test Trap
3) Refresh the page

Occurs:
The Recent Alerts table at the bottom disappears and a message pops up saying, "There was an error loading the dynamic visualization table. There is data but it is not being shown. Please refresh the page and try again."
![error loading dynamic visuals](https://cloud.githubusercontent.com/assets/12438510/7973646/bb1695b4-0a0c-11e5-8dfa-b249512c2450.png)

Often refreshing the page yields the same results.

Note: I wasn't able to reproduce this bug at will most of the time and had to refresh the page more than one in order to reproduce, though it was more consistent beforehand.

**Comment by christopherdude** [comment]
I'm not seeing this with the latest build, although please view notes on bug #155 just in case it's an SSL thing.

**Comment by davroth** [comment]
no repro w/ IE 11, Windows 8.1
