### ISSUE TITLE
Need to register www.omnim2m.net cert (i.e. The WWW part)

### ISSUE THREAD

**Issue by patrickomni** [patrickomni/omnimobileserver#154]

**Comment by christopherdude** [comment]
Visiting https://www.omnim2m.net/ (with the S in httpS) SHOULD bring you to a valid https://omnim2m.net/ page (like login) WITHOUT the WWW, maintaining the https, and no complaints about a certificate now.

**Comment by davroth** [comment]
works properly w/ IE 11 and Windows 8.1
