### ISSUE TITLE
Error comes up on ScenarioView on https://omni.net vs omni.staing

### ISSUE THREAD

**Issue by patrickomni** [patrickomni/omnimobileserver#155]
Login in https://omnim2m.net

select anyone and go to any sv page

![image](https://cloud.githubusercontent.com/assets/12114620/7976444/ede3b6c0-0a2f-11e5-8890-ce906ffb7b9f.png)

**Comment by patrickomni** [comment]
Perhaps you are fixing this already..

webMethods/ScenarioViewService.svc/GetDeviceTableData

**Comment by christopherdude** [comment]
I'm not seeing this error in the latest build, although I am seeing it online.  Please check this one again.  I'm leaving a note here JUST IN CASE this is an SSL issue reminder.

**Comment by patrickomni** [comment]
It's totally an SLL only issue (webmethod  webservice call back)

**Comment by davroth** [comment]
Repro's on https://omnistaging.azurewebsites.net/sv, IE 11, Windows 8.1; fix in V1

**Comment by davroth** [comment]
Repro's on https://omnim2m.net/sv IE 11, Windows 8.1

**Comment by christopherdude** [comment]
I am hoping that changeset 711 solves this. 

HOPEFUL fix for bug 155.  To test, please GET LATEST and PROP and run in https mode.   If you do not see a RED "There was an error:" , or  "There was an error loading the device table data:" on refrigeration, I GOT IT.

**Comment by davroth** [comment]
no repro using Chrome v43 on Windows 8.1
