### ISSUE TITLE
When sending a rule through the 2nd time with the same simulation, two rows are sent to be processed instead of one.

### ISSUE THREAD

**Issue by patrickomni** [patrickomni/omnimobileserver#156]

**Comment by patrickomni** [comment]
There are no longer two rows being processed, though there could be two messages being written.

This would be done in RulesProcessing but the daAlerts.Update() function.   Set a break point here and examine what is being written.

**Comment by christopherdude** [comment]
I think we just fixed this

**Comment by davroth** [comment]
confirmed by Chris to have been fixed
