### ISSUE TITLE
NT- Employee- Sempra Energy / Marie Van Zandt/Graph for devices is not loading

### ISSUE THREAD

**Issue by patrickomni** [patrickomni/omnimobileserver#16]
Signin without credentials, select Sempra Energy/Marie Van Zandt. 

Analyse the graph, here graph for device is not available.

![marie](https://cloud.githubusercontent.com/assets/12114620/7538317/9ee81188-f5bc-11e4-9377-d56b6839a720.JPG)

**Comment by CaseyDengler** [comment]
Device data is now there, but the UI seems a bit clunky, but that will be it's own issue.
