### ISSUE TITLE
2 error bubbles when browsing to http://omnim2m.net

### ISSUE THREAD

**Issue by davroth** [patrickomni/omnimobileserver#162]
1. Login to http://omnim2m.net as Patrick using Chrome v43, Windows 8.1
2. Select Reisner

Expected: screen displayed

Actual: 2 error bubbles (there was an error loading the device table: undefined; there was an error: undefined)
#155

**Comment by patrickomni** [comment]
Try again, this was the same as not being redirected to https. fixed.

**Comment by davroth** [comment]
redirect in place
