### ISSUE TITLE
Pest Scenario Not Showing Data In Alert Toolbar

### ISSUE THREAD

**Issue by danomni** [patrickomni/omnimobileserver#164]
Steps To Recreate
1. Go to 'Sempra Energy / Marie Van Zandt'
2. Select '--2' from 'Stations' dropdown

Expected Result:
Multiple messages, alerts, and 6 devices 

Actual Result:
None Shown
![pest station device bug](https://cloud.githubusercontent.com/assets/10458099/8068748/bfab9050-0eaa-11e5-8ef5-35badd89ec3a.jpg)

**Comment by davroth** [comment]
fixed w/ new build; no repro w/ IE 11 and Chrome 43
