### ISSUE TITLE
Data Inaccurate Or Behind In New System

### ISSUE THREAD

**Issue by danomni** [patrickomni/omnimobileserver#166]
I compared the live system to the omnim2m.net system and noticed that the Reisner tank scenario was showing inaccurate data, specifically, the graph looks like it is a few hours off on the new system from the live system. 

Screenshots attached

![screen shot 2015-06-10 at 3 42 16 pm](https://cloud.githubusercontent.com/assets/10458099/8096020/99088d94-0f87-11e5-8d06-fc5fd56b3cc0.jpg)
![screen shot 2015-06-10 at 3 42 31 pm](https://cloud.githubusercontent.com/assets/10458099/8096021/99098cee-0f87-11e5-9533-879ea96b7e90.jpg)

**Comment by davroth** [comment]
Need to look at this - could just be an anomaly, but best to check...
