### ISSUE TITLE
Graph data inconsistency between 3 day view and 24 hr view

### ISSUE THREAD

**Issue by davroth** [patrickomni/omnimobileserver#169]
The 24 hr view of data for Cowden reports no data from selected devices for the specified time period while the 3 day view appears to show data during that period.
1. Browse to https://omnim2m.net, Chrome 43, Windows 8.1, login as Patrick, click Reisner
2. Observe message on Timeline saying no data for selected device(s) during time period which defaults to 24 hrs
3. Switch view to 3 days and observe graph

Expected - no data during last 24 hrs

Actual - line graph appears to show data during last 24 hrs

![capture - 24 hr](https://cloud.githubusercontent.com/assets/12534533/8112880/9bf95e28-101f-11e5-8896-67115c871183.PNG)
![capture - 3 day](https://cloud.githubusercontent.com/assets/12534533/8112882/9e8e9d06-101f-11e5-91b1-4290511bcaaa.PNG)

**Comment by davroth** [comment]
Using https://omnim2m.net, chrome 43, windows 8.1, logged in as Patrick, and looking at Reisner account at 10:20 AM on 6/11, I see the folllowing:
• No data message for last 24 hrs (I assume this means no data since 10:20 AM on 6/10)
• Last 3 days – last report 6/10, 02:39:37 PM, 1588 gallons AND 1717 gallons
• Last 30 days -  last report 6/10, 02:38:37, 1717 gallons AND 1588 gallons

Per “time arithmetic”, there should be data on last 24 graph.

Regarding the inconsistent reports at the same time - I randomly checked 3 other time points between using both 3 & 30 day views and they seem to be identical between the views. Then, I messed around w/ cursor positioning on both 3 & 30 day graphs, and on both graphs, I was getting each of the readings above. Perhaps there is some duplicate data in the db?

**Comment by christopherdude** [comment]
I think this looks good

**Comment by davroth** [comment]
not repro'ing now, same "relative" data for 24 hr, 3 day, 30 day
