### ISSUE TITLE
Reisner Map Shows Tank Location Off Coast Of Africa

### ISSUE THREAD

**Issue by danomni** [patrickomni/omnimobileserver#170]
![screen shot 2015-06-11 at 12 09 05 pm](https://cloud.githubusercontent.com/assets/10458099/8115816/e0609dd4-1032-11e5-93b2-e361b2c07958.jpg)

**Comment by christopherdude** [comment]
This looks ok

**Comment by davroth** [comment]
looks good ib inbun2n,net - not sure where Africa came from

![capture - cowden tank location](https://cloud.githubusercontent.com/assets/12534533/8121250/cf95bbe4-105d-11e5-8f0a-4eb4b09380bf.PNG)
