### ISSUE TITLE
Reisner landing page - at-a-glance Messages box shows 0 messages but grid shows a recent message

### ISSUE THREAD

**Issue by davroth** [patrickomni/omnimobileserver#176]
1. Browse to omnim2m.net using Chrome 43, Windows 8.1, login as Patrick , select Reisner
2. View left side of landing page

Actual - Messages box in "at-a-glance " line does not match data in Summary grid below

Expected - able to reconcile the counts

![capture - message count](https://cloud.githubusercontent.com/assets/12534533/8174378/b8e379e6-1390-11e5-834f-cd039d0e0468.PNG)

**Comment by patrickomni** [comment]
Yes it does.  0 messages, 1 alert.  A message is something that is reported and triggers a rule, but does not send an alert.  If you would like this changed, please specify.

**Comment by davroth** [comment]
Ok, understand that Messages are the "normal" reports and Alerts are those that violate any established rule(s). However, when I look at Reisner, I still see 0 message in the "at-a-glance" line while the Last Report grid shows a normal report (e.g., didn't trigger an alert per rule) having occurred an hour ago (writing this message at 20:09 on 22-Jun). So there's something i'm still missing. Can we talk?

![capture - reisner count not explained](https://cloud.githubusercontent.com/assets/12534533/8298272/83275fb2-191b-11e5-8a8e-14cd13a2695d.PNG)
