### ISSUE TITLE
Time Zone Incorrect For Sempra Scenario

### ISSUE THREAD

**Issue by danomni** [patrickomni/omnimobileserver#179]
All time stamps are in UTC

**Comment by davroth** [comment]
Chris, can you check this? I don't know when traps actually reported, but our times are 7 hrs earlier than those shown by Caldera so i'm wondering whether we're using Pacific time?

High order bit here: we need to understand the data being shown on the screen so we can explain it.

**Comment by patrickomni** [comment]
The time of the alert is correct.  What we are missing is a spec on the alert date of the insertdate of the alert.

However, some devices report the date in which the message was recorded, and in others, we derived this date from the insertedate.  After which, the messagedate (whether from the device or derived from the insert date) is offset based upon the GeoLoc of the device.

But the alert is not a device and does not have a position.  So the question is, what is the correct thing to do here?

We can set it to the MessageDate, which may be old, the insertdate (which it is now), or the insertdate offset with the GeoLoc (new code).

Please specify.

**Comment by davroth** [comment]
There are different issues in play here:
1. What is timezone of the date/time stamp? 
2. How do we correlate a message in the Summary grid w/ a message in the Recent Alerts grid?
3. W/ a Caldera gateway potentially reporting status for multiple traps, are we sure that Recent Alerts table is displaying all alerts that were sent? (#183)
1. Best if timezone can be adjusted to match the timezone where device is located. We must be able to explain the timezone to customers. Looking at the message for Gateway 5, it looks as if we are using UTC (which is fine...)
2. Understand the potential time difference between message receipt and time alert sent. Gateway 5 appears to have sent an alert 11 hrs after the message was received. That seems like a long time, so perhaps the time delta is a result of using a different time zone? I know real estate is tight, but would it be possible to have 2 date/time columns - 1 for message date/time, the other for alert sending?

**Comment by patrickomni** [comment]
1. Timezone is currently UTC of Server
2. You cannot correlate an alert to the summary grid in that there may be N per device, but you can select the device from the summary which will filter it to show the alerts for that device.
3. They should be now (since yesterday's fix).

We can surely adjust the time zone to the time zone of the device.  It's a reasonable call.  Just verify and I'll patch that.

**Comment by davroth** [comment]
fixed
