### ISSUE TITLE
Need to show recent alerts table on each scenario

### ISSUE THREAD

**Issue by patrickomni** [patrickomni/omnimobileserver#18]
(same as traps data table).

I need to ensure data is correct then Chris can finish

**Comment by CaseyDengler** [comment]
Not sure what I'm looking for on this one, could you explain a bit more?

**Comment by CaseyDengler** [comment]
I'm assuming this has to do with the sub sections of "Stations" for Traps.
Looking at --1 for Traps, there appears to be no Device Data shown.
![trap 1 device data blank](https://cloud.githubusercontent.com/assets/12438510/7713314/d61a8448-fe2b-11e4-8559-f30057f478a0.png)

While Stations has the Device Data filled out with a table
...Well, I would have shown that, but I've just found a new issue that prevents me from seeing the data...

Might be related to another issue, #42

**Comment by patrickomni** [comment]
Yes, this one is related to #42.   Let's track it there.
