### ISSUE TITLE
Sempra - at-a-glance Messages counter not incrementing when Station 2 is selected

### ISSUE THREAD

**Issue by davroth** [patrickomni/omnimobileserver#180]
1. Browse to omnim2m.net w/ Chrome 43, Windows 8.1, log in as Patrick, select Sempra
2. Devices filter in upper left shows by default
3. Click dropdown and select Station --2
4. Observe at-a-glance Messages box

Expected - number of Messages in the box to minimally match the number of messages displayed in the Summary grid below

Actual - Messages box shows 0 while there are 6 messages in the Summary grid below.
![capture - sempramessagecount](https://cloud.githubusercontent.com/assets/12534533/8195484/c7b24c3e-1437-11e5-88f6-66514e352f3c.PNG)
#176 #177

**Comment by patrickomni** [comment]
Fixed
