### ISSUE TITLE
Sempra - what is time zone used in Recent Alerts grid?

### ISSUE THREAD

**Issue by davroth** [patrickomni/omnimobileserver#182]
The time stamp in the Recent Alerts table cannot be easily tied to anything in the Summary table. We believe the entries for Trap 2-2 in both the Summary table and the Recent Alerts table result from the same message - but they are 11 hrs apart. If these are from the same message (and they may not be) , then the displayed time stamps should be very close.
![capture - timezone discrepancy](https://cloud.githubusercontent.com/assets/12534533/8213066/3abdb244-14d4-11e5-9592-453c73dbac59.PNG)

**Comment by davroth** [comment]
#179

**Comment by patrickomni** [comment]
This is the same as #179 so I am closing
