### ISSUE TITLE
Sempra Recent Alerts grid - only displays first trap reporting

### ISSUE THREAD

**Issue by davroth** [patrickomni/omnimobileserver#183]
1. Browse to omnim2m.net, Chrome 43, Windows 8.1, login as Patrick, select Sempra
2. Observe Summary Grid has 5 recent reports from Trap 2
3. Observe Recent Alerts shows a line from the lastest time period for Trap 2-2

Expected - either display nothing in the Recent Alerts table because all traps were armed OR display all the recent reports

Actual - Summary Grid shows 5 rows while only 1 row (which isn't really an alert...) shows in Recent Alerts table
#182

https://cloud.githubusercontent.com/assets/12534533/8213066/3abdb244-14d4-11e5-9592-453c73dbac59.PNG

**Comment by davroth** [comment]
The concern here is that the Recent Alerts table seems to show the first line from a Gateway's report. If a Gateway report has 2-2 reporting first as Armed and 2-4 reporting as triggered later in the same Gateway report, will the triggered alert be sent?

**Comment by patrickomni** [comment]
This isn't making sense to me.  However, if there were any issues around alerts not being sent, its because data was not being sent to our system.

Is this the one you talked to Chris about?

**Comment by davroth** [comment]
Can we simulate this situation? 
     A single report from Gateway N contains status for Traps 1, 2, and 3 in that order. Traps 1 & 2 report
     that they are armed. Trap 3 reports it has been triggered. What does the Recent Alerts table show?

Expected - Traps 1, 2, and 3 reported in Recent Alerts table OR Trap 3 only reported in Recent Alerts table

**Comment by patrickomni** [comment]
We need hardware to do so

**Comment by davroth** [comment]
fixed
