### ISSUE TITLE
Able to add in blank information to User list

### ISSUE THREAD

**Issue by CaseyDenglerOmni** [patrickomni/omnimobileserver#186]
Steps:
1) Log into Omni
2) Edit in a new user into any account
3) Leave information as blank except for a phone number
4) Attempt to have omni send a message to the blank user's phone

Expected:
The user receives whatever message is being sent through

Occurs:
The message does not go through to the user

Note: Really, there shouldn't be any reason to have sections of the Add User thing blank (maybe except email), but the refusal to send information seems more pressing.

**Comment by patrickomni** [comment]
fixed

**Comment by CaseyDenglerOmni** [comment]
Specific issue is solved, closing
