### ISSUE TITLE
Alerts not being sent for Roxy 2 in Omni Demo

### ISSUE THREAD

**Issue by CaseyDenglerOmni** [patrickomni/omnimobileserver#187]
Steps:
1) Log into Omni
2) Impersonate "Omni Demo"
3) Force the device to fall outside of it's alert range (or whatever it's called)
4) Observe the rules for Roxy 2 and the recent data for the device

Expected:
The page shows that an alert has been sent for Roxy 2, saying that it has fallen outside of its normal range.

Occurs:
Although the data is recorded, no alert is being sent through, either for phones or on the web page

**Comment by patrickomni** [comment]
I had a similar issue with Test Tank at the site level.  But it worked fine for Reisner.

**Comment by davroth** [comment]
Is this related to #202?

**Comment by patrickomni** [comment]
No repro anymore.  I think it was a moment in time.
