### ISSUE TITLE
Rules UI - "additional phone numbers" presents security risk

### ISSUE THREAD

**Issue by davroth** [patrickomni/omnimobileserver#195]
Allowing a user to put unverified phone numbers on alert notifications poses a potential security risk. While this is useful as a debugging tool (we can easily add our own phones), this also presents a backdoor for someone to put a random phone number into a rule in a way that can be hard to detect.

We can reduce the attack surface area to a single location by only allowing Account Users to be selected in the Rules UI.

Regarding debugging - or adding ourselves to receive notifications -
1. Add an "Enable debugging" checkbox. The checkbox is visible to all, but writeable only by Omni Admin or Partner Admin
2. If the box is selected, then allow user to select from authorized administrators

**Comment by patrickomni** [comment]
I've simplified this and just like simulate, only I can change these now.
