### ISSUE TITLE
Live Data check box not working 

### ISSUE THREAD

**Issue by CaseyDenglerOmni** [patrickomni/omnimobileserver#196]
Steps:
1) Log into Omni (staging)
2) Impersonate Fridge Sample
3) Set the data filter to 30 days
4) Observe the data on the graph
5) Click on Show live data
6) Observe the data (or lack thereof) on the graph

Expected:
The data on the graph shows the data for the past 30 days while updating the new information every 5 seconds.

Occurs:
The graph goes blank, showing no data what so ever. The graph does flash every (I assume) 5 seconds, as if trying to write new data to it.

The graph before selecting Live data
![live data before](https://cloud.githubusercontent.com/assets/13022216/8484384/52a3281a-20ac-11e5-8282-d4f3af57c5b3.png)

The graph after selecting Live data
![live data after](https://cloud.githubusercontent.com/assets/13022216/8484671/ba6c3634-20ad-11e5-9fd4-19a3723c3597.png)

Note: Originally thought that the graph was showing data for the first 24 hours after hitting Live data because the 24 hour data was blank as well. After testing the same issue with Reisner Distributor, which does have information from the past 24 hours, I have conformed that the graph becomes blank when selecting Live data.

**Comment by peters95** [comment]
this is fixed. moved live data to the dropdown. removed the checkbox. fixed the refresh glitch in live data.
