### ISSUE TITLE
Filtering to any sub section yields a blank page on Chrome

### ISSUE THREAD

**Issue by CaseyDenglerOmni** [patrickomni/omnimobileserver#199]
Steps:
1) Open up Chrome
2) Log into Omni
3) Impersonate Sempra
4) Click on the site drop down box and select any station number

Expected:
The data is filtered to fit the selected sub-section.

Occurs:
The page comes up as completely blank.

Note: I assume this is related to an issue from earlier where the site would freeze for Chrome when trying the same thing, so I don't think this is an issue on our side. I'll try to find that issue and relate it to this one if I find it.

**Comment by patrickomni** [comment]
I think this is a dupe but it was missed because I didn't set the milestone

**Comment by patrickomni** [comment]
fixed

**Comment by davroth** [comment]
re-pro's this morning; possibly related to fixing "Please wait" ?

**Comment by davroth** [comment]
not fixed related to fix of #211 ?

**Comment by davroth** [comment]
oops #205

**Comment by CaseyDenglerOmni** [comment]
I'm also still able to reproduce on my side.

**Comment by peters95** [comment]
I have a fix for this now check in to TFS. Working w/ Pat to publish out to nettelpong.azurewebsites.net bear with me a little while

**Comment by peters95** [comment]
patrick is publishing this closing this now

**Comment by christopherdude** [comment]
New fix for this one with changeset 848.  The fix that was introduced caused more problems.  It wasn't the correct solution.  Now it works.
