### ISSUE TITLE
Multiple users account with same user name and role Id

### ISSUE THREAD

**Issue by patrickomni** [patrickomni/omnimobileserver#2]
Sign in with without credentials, Add new account, and then enter Users details with same Role ID type and same user's data like  First and Last Name and other data.  It is creating multiple user account's with similar user account.
![multiple_user](https://cloud.githubusercontent.com/assets/12114620/7517366/40949176-f4f2-11e4-8192-576e2fe91434.PNG)

**Comment by patrickomni** [comment]
This is all wrapped up in that single user issue. Bug #25 .   Once that is fixed retest this.

**Comment by CaseyDengler** [comment]
Looks good here
