### ISSUE TITLE
Sempra V1.0 - Recent Alerts table showing duplicate data

### ISSUE THREAD

**Issue by davroth** [patrickomni/omnimobileserver#200]
9-Jul - Sempra's Recent Alerts table is showing what appear to be duplicate entries for reporting traps. This may be a result of recovering from the bad data inadvertently fed into the system recently.

![capture - duplicate alerts](https://cloud.githubusercontent.com/assets/12534533/8603830/7c98b940-262f-11e5-9671-cffcc06e8565.PNG)

**Comment by davroth** [comment]
Caldera's site shows that 6 devices reported on 2-Jul, with nothing having reported since
![capture - caldera results](https://cloud.githubusercontent.com/assets/12534533/8604241/3080af10-2632-11e5-839a-5e8d205e6c64.PNG)

**Comment by patrickomni** [comment]
This is on the production site

**Comment by danomni** [comment]
Hi Dave & Patrick,

The Caldera page you are looking at only shows reports for traps & gateways
and not solely gateways.

This is why you are seeing data on the production site that is not on the
Caldera reporting URL.

Dan

On Mon, Jul 13, 2015 at 1:21 PM, patrickomni notifications@github.com
wrote:

> This is on the production site
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/patrickomni/omnimobileserver/issues/200#issuecomment-121045031
> .

## 

Dan Clem | *Marketing Manager *

Dan@omnim2m.com dan@omnim2m.com | (425) 279-7997 | omnim2m.com

https://www.linkedin.com/in/danclem [image: https://twitter.com/omnim2m]
https://twitter.com/omnim2m  https://www.facebook.com/omnim2m
https://plus.google.com/+Omnim2m

**Comment by patrickomni** [comment]
Not repro
