### ISSUE TITLE
Reisner Alerts - don't appear to be sent when rule violated

### ISSUE THREAD

**Issue by davroth** [patrickomni/omnimobileserver#202]
1. Browse to https://omnim2m.net/sv#, log in as Patrick, select Reisner
2. Landing page shows 14.14% remaining; Active Alerts table is empty
3. Check rules config - device level rule set to trigger when below 20%

Expected - Alert to have been sent; alert displayed in Active Alerts table

Actual - Active Alerts table is empty; Twilio shows no SMS messages sent since July 8 when the tank level was above the 20% threshold
![capture - cowden no alerts](https://cloud.githubusercontent.com/assets/12534533/8624038/de4654e4-26e9-11e5-87a8-7852d39987b8.PNG)
![capture-cowden device rule](https://cloud.githubusercontent.com/assets/12534533/8624047/e79f316e-26e9-11e5-8040-0db1fb20359c.PNG)

**Comment by davroth** [comment]
I noticed during the Investor mtg that the rule had somehow gotten set to 6% (Pat and I talked about it during the demo). Yesterday (Thu), after checking w/ Gary to verify the correct setting, I reset both account level and device level rules to 20%...

**Comment by davroth** [comment]
Production site - Reisner global rule set to fire @ 20% w/ msgs sent to Dan, Jeff, Denny and 3 additional ph numbers (Gary, Chris, Patrick); no device level rule set
8 AM report shows 18.56% remaining.
Rule should have fired, but no results showing in Active Alerts graph
Twilio shows 4 text messages were sent starting @ 08:52 this morning – each of the Reisner employees were sent a text and there was a 4th msg sent to Patrick. Interestingly, his is the last of the 3 numbers listed in “additional phone numbers”.

**Comment by peters95** [comment]
I am testing this out to see if the rule fires when the tank drops below 85%. I set the device rule additional phone number to me and set it active

**Comment by patrickomni** [comment]
The rule is still incorrect; by default, no one will receive anything.  Removing bug tag
