### ISSUE TITLE
Rules UI - color code override warning to make it more obvious

### ISSUE THREAD

**Issue by davroth** [patrickomni/omnimobileserver#204]
When the Rules UI is invoked at a level that will cause another existing rule to be overridden, a message is displayed. There is a request to make this message "jump out" more obviously to users. Today, the message has in normal font and has a blue checkbox.

The request is to
1. place the word Caution in bold font at the top of the message
2. change the color of the OK button to Green (thought about Red, but that's not an error; thought about Yellow, but that might not be visible)

**Comment by davroth** [comment]
![capture - override warning](https://cloud.githubusercontent.com/assets/12534533/8635079/c55a7e58-27c8-11e5-8766-bc8b24edbf4a.PNG)

**Comment by davroth** [comment]
![capture - override warning](https://cloud.githubusercontent.com/assets/12534533/8656684/fd918d80-294d-11e5-825c-30f3447730ad.PNG)

**Comment by davroth** [comment]
We've lost the yellow caution button which was what was specifically requested. 
Text for box: "Saving a rule here will override a site level rule for this Device"

**Comment by christopherdude** [comment]
Big yellow caution in there now
