### ISSUE TITLE
Nettelpong - no results displayed when "scope" of display is filtered

### ISSUE THREAD

**Issue by davroth** [patrickomni/omnimobileserver#205]
Code not yet released, but want to make sure we don't miss this:
1. Browse to http://nettelpong.azurewebsites.net/sv, Chrome 43, Windows 8.1, log in w/o Id, select Sempra
2. On landing page, click Stations drop down (upper left corner) and select 4

Expected - At-a-glance chiclets, Summary grid, map, Active Alerts grid w/ Station 4 devices

Actual - blank screen; back button remains active

**Comment by davroth** [comment]
Behavior has changed - now "Please wait message" is displayed and control is never returned to user
#211

**Comment by patrickomni** [comment]
Don't know if this is helpful Chris but I get:
Uncaught TypeError: Cannot read property 'PRM_ParserErrorDetails' of undefined

**Comment by patrickomni** [comment]
fixed

**Comment by davroth** [comment]
No longer see "Please wait message", but the screen stays blank (#199)

**Comment by peters95** [comment]
cool im taking a look into this now

**Comment by davroth** [comment]
closing as duplicate of #199
