### ISSUE TITLE
Omni Demo - "Error loading the device table data: undefined"

### ISSUE THREAD

**Issue by davroth** [patrickomni/omnimobileserver#210]
1. Browse to http://nettelpong.azurewebsites.net/sv, Chrome 43, Wkndows 8.1, login anonymously, select Omni Demo
2. Set time filter to 3 months (or 6 months)

Expected - all structures load successfully

Actual - red bubble in lower left corner informing me there was an error loading the device table data: undefined

**Comment by davroth** [comment]
30 days works for Omni Demo (on Chrome) but 3 months shows the "red bubble"

**Comment by patrickomni** [comment]
fixed

**Comment by davroth** [comment]
Seeing new error on Chrome: A column named '.' already belongs to this Data Table'

**Comment by peters95** [comment]
added in the missing row for resource for fridge.summary.finalalerts and now this is working as expected
