### ISSUE TITLE
Rules UI - saving device level rule does not return control to user

### ISSUE THREAD

**Issue by davroth** [patrickomni/omnimobileserver#211]
1. Browse to http://nettelpong.azurewebsites.net/sv, Chrome 43, Windows 8.1, login anon, select Omni Demo
2. Click on hyperlink for any device to bring up Rules UI
3. Make a change to Rules UI and click Save Rule

Expected - rule saved and control returned in reasonable amount of time

Actual - rule is saved, but the "Please wait..." box stays on the screen for at least 2 minutes (I didn't wait any longer). Hitting refresh button returns me to the page and when I check rule, I see my updates saved.

**Comment by patrickomni** [comment]
fixed (Finally)

**Comment by davroth** [comment]
fixed
