### ISSUE TITLE
Device level rules UI - "should not have hit" error

### ISSUE THREAD

**Issue by davroth** [patrickomni/omnimobileserver#214]
1. Browse to http://nettelpong.azurewebsites.net/sv# , chrome 43, windows 8.1, login anon, select Sempra
2. Click Device 15.1 in summary grid to bring up rules ui

Expected - warning message that parent level rules will be overridden

Actual - message saying 'Should not have hit'

![capture - should not have hit](https://cloud.githubusercontent.com/assets/12534533/8681685/d2701c86-2a1d-11e5-9844-1f3517a20376.PNG)

**Comment by patrickomni** [comment]
You caught me mid-deploy.

Fixed :)
