### ISSUE TITLE
Highlights needs to reflect date filter

### ISSUE THREAD

**Issue by patrickomni** [patrickomni/omnimobileserver#216]
Align tank and fridge to Traps

**Comment by patrickomni** [comment]
Dave,

This is for summary highlights to respect date filter.

Not as easy as I thought.  I've prepared the server side ASP and the backend for this, however, since the date selector drives client side, we need some wiring here.  Sending to Dave for comment.   Dave this could cost a day or so.  Or I can pick a reasonable default for now (and change the labels like -> Active Alerts (last 24 hours)

**Comment by davroth** [comment]
I like your idea; can we use last 3 days?

**Comment by patrickomni** [comment]
These now are set to 3 days

![image](https://cloud.githubusercontent.com/assets/12114620/8708057/93407c3c-2aee-11e5-9287-3cd0d419645a.png)
