### ISSUE TITLE
Rules UI - add hyperlink to User Guide

### ISSUE THREAD

**Issue by davroth** [patrickomni/omnimobileserver#218]
add a hyperlink to Rules UI at global account, group, device levels that includes a hyperlink to the Rules UI user guide (request from Gary/Dan)

**Comment by patrickomni** [comment]
Oh, that's not how I implemented.  I put it at the top of the whole page.   Where would you like it, in the RulesUI dialog?

**Comment by davroth** [comment]
oops - forgot to include where:
1. Landing page title bar - i'm also creating a Landing Page UG, so can we put a dropdown control w/ each choice being a link to a (probably PDF) document that opens when clicked?
2. Rules dialog title bar - hyperlink to UG

**Comment by davroth** [comment]
Please have doc pop up in new window (not just tab) - can be used side-by-side w/ screen that way

**Comment by peters95** [comment]
this is done now. I need the second guide please to update accordingly.

**Comment by peters95** [comment]
both have been added and have been checked in

**Comment by davroth** [comment]
From comment above - 2. Rules dialog title bar - hyperlink to UG

Need access to user guides from Rules UI window. We just need the Rules UI UG in the Rules UI title bar, but if it's easier to put the dropdown list in, then do that

**Comment by peters95** [comment]
hey dave

does this have to be in the Rules UI.. this will require significant time investment to do

**Comment by davroth** [comment]
we can defer; not willing to spend 6 hrs on this right now
