### ISSUE TITLE
Recent reported times are going backwards on the Summary Table

### ISSUE THREAD

**Issue by CaseyDenglerOmni** [patrickomni/omnimobileserver#224]
Steps to reproduce:
1) Log into omni on two separate pages
2) Impersonate Test Tank on both pages
3) Wait about three minutes
4) Refresh only one page and compare the recent times between the two pages

Expected:
The time on the refreshed page should either not change, or it should go forward in time

Occurred:
The time on the refreshed page is farther back than the time on the older page, which couldn't be possible because the time is supposed to represent the last reported time, which couldn't go back in time.

The time on the devices before the refresh
![time before refresh](https://cloud.githubusercontent.com/assets/13022216/8713995/ee56b290-2b24-11e5-9e94-581f102dfcb3.png)

The time on the devices after the refresh
![time after refresh](https://cloud.githubusercontent.com/assets/13022216/8714002/ffa6f172-2b24-11e5-83f5-dd076d31d7a9.png)

Note: This could be related to an earlier bug that I reported about simulations where, when the user would attempt to simulate something, the data change would occur in the past, affecting an earlier part of the graph. If I can find the bug, then I'll post it here.

**Comment by davroth** [comment]
18-Jul - could not repro; can we close?
