### ISSUE TITLE
On IE, changing the rules sometimes causes the site to hang

### ISSUE THREAD

**Issue by CaseyDenglerOmni** [patrickomni/omnimobileserver#226]
Steps:
1) Log into Omni
2) Impersonate Test Tank
3) Change the rules for either device or site level
4) Save the rules
5) If the site does not hang, repeat steps 3 and 4 at most three times. If nothing happens, then close this bug.

Expected:
The site saves the rules and lets the user carry on interacting with the page

Occurs:
The site seems to freeze up with a simple "Please wait..." bar showing with everything else shaded dark.

![please wait hang](https://cloud.githubusercontent.com/assets/13022216/8714298/1fbbced0-2b28-11e5-8f7d-aa266c4c3a25.png)

Note: This error does not always occur. If you cannot reproduce it after three tries, please let me know and feel free to close it.

**Comment by davroth** [comment]
#211 -  same problem but using Chrome 43 rather than IE

**Comment by patrickomni** [comment]
Finally, finally fixed :)
