### ISSUE TITLE
Odd error window popping up on IE when refreshing Sempra

### ISSUE THREAD

**Issue by CaseyDenglerOmni** [patrickomni/omnimobileserver#227]
Steps:
1) Log into Omni
2) Impersonate Sempra
3) Refresh the page

Expected:
The page refreshes with no issues

Occurs:
This odd error window pops up
![odd error](https://cloud.githubusercontent.com/assets/13022216/8714434/8addcafa-2b29-11e5-8fc9-c5b533a48d9a.png)
Don't know what else to say beyond that honestly. Seems extremely out of place.

**Comment by patrickomni** [comment]
Good catch! SHould be fixed; re-run tests.

**Comment by CaseyDenglerOmni** [comment]
Can't reproduce
