### ISSUE TITLE
Online User Guides - open in separate windows

### ISSUE THREAD

**Issue by davroth** [patrickomni/omnimobileserver#229]
Please have doc’s each open in a separate window. That will allow side-by-side viewing

**Comment by patrickomni** [comment]
Fixed though waiting on final documet

**Comment by peters95** [comment]
this has been checked in now using window.open... in Chrome it continues to behave the way the user specified however in their settings due to the browser overriding it. I test with both ahref and window.open and both behaved the same inside of Chrome.
