### ISSUE TITLE
Scenario Name Misspelled In Account Add Screen

### ISSUE THREAD

**Issue by danomni** [patrickomni/omnimobileserver#23]
'Refridgeration' appears under scenario name

**Comment by patrickomni** [comment]
Ugh :( 

Fixed :)  Will be in next build

**Comment by danomni** [comment]
Cool. Just for the sake of forgetting this issue, I am not closing it until the build is propped. Might forget it otherwise :)

**Comment by patrickomni** [comment]
Should have been propped immediately (database item)

**Comment by CaseyDengler** [comment]
Basic spelling skills achieved
