### ISSUE TITLE
Active Alerts Status values - relevant to whether text message has been sent

### ISSUE THREAD

**Issue by davroth** [patrickomni/omnimobileserver#232]
1. Browse to http://nettelpong.azurewebsites.net/sv, Chrome 43, Windows 8.1, login as dave, select Test Traps
2. Observe Active Alerts table

Expected - status to describe whether SMS has been Delivered, is Pending (waiting for working hours)

Actual - status value of New

Alerts also have a status value of Active (needs attention), Assigned (someone has been asked to work on it), Cleared (Joe looked at problem and its no longer a problem)

**Comment by patrickomni** [comment]
new means that you didn't actually set it to be sent as an SMS so just an alert was created.  It will show  (should show) sent when sent and pending when pending

**Comment by davroth** [comment]
added to user guide
