### ISSUE TITLE
Map - displaying too many devices for device selection filter

### ISSUE THREAD

**Issue by davroth** [patrickomni/omnimobileserver#240]
1. Browse to https://nettelpong.azurewebsites.net/sv, chrome 43, windows 8.1, login as dave, select Sempra
2. set device scope filter to 1, observe map
3. increase scale of map by clicking '+' until you can see all the devices

Expected - 7 lollipops

Actual - a very large number of lollipops
![capture - too many devices](https://cloud.githubusercontent.com/assets/12534533/8763656/d12c16f8-2d5c-11e5-9485-69e9a40d25fd.PNG)

**Comment by davroth** [comment]
Devices no longer showing on the map
![capture - sempra no devices](https://cloud.githubusercontent.com/assets/12534533/8780801/33bb5054-2ec0-11e5-87e0-4c1f361b8b74.PNG)

**Comment by davroth** [comment]
Here are current repro steps:
1. browse to https://nettelpong.azurewebsites.net/sv, chrome 43, windows 8.1, login as dave
2. select Sempra and observe landing page has map 
3. zoom out to locate Hawaii, then zoom in

Expected: lollipops to show up on Maui

Actual: no lollipops until device scope is filtered to a station. I filtered to station 2, saw lollipops, then set scope back to global (Stations) and the lollipops appear

**Comment by christopherdude** [comment]
I think this was fixed with my other fix
