### ISSUE TITLE
Sempra map - no devices displayed on initial entry to landing page

### ISSUE THREAD

**Issue by davroth** [patrickomni/omnimobileserver#242]
fixing #240 appears to have caused this
1. browse to https://nettelpong.azurewebsites.net/sv, chrome 43, windows 8.1, login as dave
   1. select Sempra and observe landing page has map 
   2. zoom out to locate Hawaii, then zoom in

Expected: lollipops to show up on Maui

Actual: no lollipops until device scope is filtered to a station. I filtered to station 2, saw lollipops, then set scope back to global (Stations) and the lollipops appear
![capture - sempra no devices](https://cloud.githubusercontent.com/assets/12534533/8781424/bc788b16-2ec3-11e5-9679-97a8bed50c94.PNG)

**Comment by christopherdude** [comment]
I believe this was fixed with my other fix.
