### ISSUE TITLE
Checkboxes and Graph not communicating properly

### ISSUE THREAD

**Issue by ghost** [patrickomni/omnimobileserver#246]
Description: When a checkbox is deselected, it takes a few seconds to load properly (it shows the old graph while loading).  This could just be an efficiency thing that gets better with time, but I thought it would be worth bringing up.  Bigger problem is that the graph sometimes DOES NOT load, or will load, and then revert to a previous state, where the graph does not match the checkboxes.
![check box and graph bug](https://cloud.githubusercontent.com/assets/13140317/8813182/4755a00a-2fb6-11e5-86de-22f3eca0d9aa.PNG)

Steps to Reproduce: Deselect one of the checkboxes.  Leaving the window and then returning to it (by means of alt-tabbing, for example), will return the graph to a previous state - one that does not match the check boxes.

Actual Results:  The graph does not match the checkboxes.  

Expected Results:  Regardless of alt-tabbing or otherwise leaving the window, the graph should always match the checkboxes

**Comment by davroth** [comment]
I couldn't repro this on Chrome V43, Windows 8.1 using OmniDemo account.

**Comment by patrickomni** [comment]
Fixed
