### ISSUE TITLE
Blank Labels can be saved

### ISSUE THREAD

**Issue by ghost** [patrickomni/omnimobileserver#249]
Description: User is allowed to edit labels and save them off as blanks.  Because of the way the editing process works, user can no longer edit the blank labels, since there is nothing to select.
![blank label bug](https://cloud.githubusercontent.com/assets/13356999/8814342/2cf07140-2fc0-11e5-9c62-58b39b4e83e7.PNG)

Steps to Reproduce: Edit a label, then save it off as a blank

Actual Results: Label can no longer be edited

Expected Results: User should not be allowed to save off a blank label OR one should be allowed to edit the label after it is saved as blank

**Comment by christopherdude** [comment]
I have fixed this.. get latest.  This is also a duplicate bug

**Comment by davroth** [comment]
I still see this w/ Chrome - but I think we can punt it
![capture - blank label](https://cloud.githubusercontent.com/assets/12534533/8853865/b5ba2db6-3111-11e5-9bd4-357b44e8510e.PNG)

**Comment by patrickomni** [comment]
Ok, no more fixing bugs :)
