### ISSUE TITLE
Scroll bar disappearing

### ISSUE THREAD

**Issue by ghost** [patrickomni/omnimobileserver#250]
Description: After changing site/device-level rules and saving, the scroll bar for the page disappears and user can no longer scroll
![scroll bar disappearing bug](https://cloud.githubusercontent.com/assets/13356999/8814642/ac79f992-2fc3-11e5-911f-69fb979f7600.PNG)

Steps to Reproduce: save off site/device-level rules (no need to change anything).

Actual Results: Scroll bar disappears, and can no longer scroll using any means (arrow keys, spacebar, etc.)

Expected Results: Scroll bar should NOT disappear, and I should still be able to scroll on the page

**Comment by christopherdude** [comment]
This was fixed in previous build

**Comment by patrickomni** [comment]
This was a propping issue we believe.  Please rcheck

**Comment by patrickomni** [comment]
This is fixed

**Comment by ghost** [comment]
This is still an issue in both IE and Chrome

**Comment by patrickomni** [comment]
Punting,

**Comment by christopherdude** [comment]
This actually works in my build.

Sent from my Windows Phone
