### ISSUE TITLE
Active Alerts grid - "Message" cell for alert row is empty in Test Tanks

### ISSUE THREAD

**Issue by davroth** [patrickomni/omnimobileserver#254]
This may be "by design" w/ no msg configured, but want to capture it
1. Browse to https://nettelpong.azurewebsites.net/sv#, Firefox 38, Windows 8.1, login as dave, select Test Tank
2. Set time filter to last 3 days and observe Active Alerts grid has a row

Expected - Message cell tells me what is wrong

Actual - Message cell is blank
![capture - empty message cell](https://cloud.githubusercontent.com/assets/12534533/8832520/6c56c5de-305e-11e5-9210-a6adee1e0201.PNG)

**Comment by patrickomni** [comment]
Verified this was left over development cruft on test data.   I retriggered the alert and this now say the full message
![image](https://cloud.githubusercontent.com/assets/12114620/8839217/3620e4e8-3088-11e5-8a8c-d9899dadd79a.png)

**Comment by davroth** [comment]
data problem - fixed

**Comment by davroth** [comment]
Many of the Active Alerts rows for Sempra are also showing blank message lines; are these also the result of dirty test data?

**Comment by peters95** [comment]
taking a peek now

**Comment by peters95** [comment]
I believe this related to bad test data.. please see the below data output of 30 days of alerts for one of sempura's site = 37

Id  DeviceId    ResolvedRowId   MessageType Severity    StatusId    MessageResourceId   RulesId PrimaryData1    ActivityURL FinalMessageText    DeviceLabelId   SiteId  ContactId   InsertDate  UpdateDate
18868   7   1396124 1   1   0   Alert.Message.Traps.0   1351    0   NULL    Trap #1.1 has been triggered.   0013A20040B75626            37  1   2015-07-22 12:59:33.120 NULL
18866   7   1396118 1   1   0   Alert.Message.Traps.0   1351    0   NULL    Trap #1.1 has been triggered.   0013A20040B75626            37  1   2015-07-22 12:06:49.980 NULL
18839   1   1395918 1   1   1   Alert.Message.Traps.0   1350    0   NULL    NULL    0013A20040B752CE            37  1   2015-07-20 17:13:03.350 NULL
18838   1   1395916 1   1   1   Alert.Message.Traps.0   1350    0   NULL    NULL    0013A20040B752CE            37  1   2015-07-20 17:12:51.877 NULL
16483   1   1374599 1   1   2   Alert.Message.Traps.0   1290    0   NULL    Trap #1-2 has been triggered.   0013A20040B752CE            37  1278    2015-07-01 07:25:14.057 NULL

if you notice finalmessagetext is null twice. this is why the message text is empty in the alerts grid.

**Comment by patrickomni** [comment]
This was midstream development
