### ISSUE TITLE
At a glance summary - Active Alerts cell doesn't show alerts when grid does

### ISSUE THREAD

**Issue by davroth** [patrickomni/omnimobileserver#256]
1. Browse to https://nettelpong.azurewebsites.net/sv, Firefox 38, windows 8.1, login as dave, select Test Traps
2. Set time filter to last 3 days and observe page

Expected - at-a-glance (AAG) cell for Active Alerts matches Active Alerts grid

Actual - AAG cell says 0, but grid shows many alerts

![capture - active alerts mismatch](https://cloud.githubusercontent.com/assets/12534533/8832982/fc8c8c54-3060-11e5-808d-721d99c9ba59.PNG)

**Comment by davroth** [comment]
Same results observed for Test Fridge - at-a-glance cell for Active Alerts shows 0 and Active Alerts grid shows many alerts for 7/21 when time filter is set to 3 days

**Comment by peters95** [comment]
fixed the stored proc to return the correct value now
