### ISSUE TITLE
'Devices' Tab is Broken

### ISSUE THREAD

**Issue by danomni** [patrickomni/omnimobileserver#26]
Under 'Add Account' screen, 'Devices' tab is broken

**Comment by patrickomni** [comment]
Let's remove this device tab.

**Comment by patrickomni** [comment]
Removed.  Dan, after we prop the new build and you verified this is fixed, please close or send back to me.

**Comment by danomni** [comment]
Ok. I will close this issue once you reintroduce it in the new build.

**Comment by patrickomni** [comment]
Staged
