### ISSUE TITLE
At a glance summary - "Reported w/in 24 hrs" cell doesn't agree w/ data in summary grid

### ISSUE THREAD

**Issue by davroth** [patrickomni/omnimobileserver#262]
1. browse to https://nettelpong.azurewebsites.net/sv, FireFox 38, windows 8.1, login as dave, select Test Traps
2. Set time filter to last 30 days
3. Observe at a glance (AAG) summary cell for "Reported within 24 hrs" and observe that 4 devices have reported since 7/20

Expected; AAG "Reported within 24 hours" to have "4"

Actual: AAG "Reported within 24 hours" has "3"

![capture - aag reported within 24 hours](https://cloud.githubusercontent.com/assets/12534533/8837243/36b2d226-307a-11e5-8be6-aa57998dea55.PNG)

**Comment by danomni** [comment]
Question:

Why would it show 4, since the fourth data point is on the 20th and today is the 22nd? 

Wouldn't that indicate a time of over 24 hours?

**Comment by patrickomni** [comment]
Yes, this is by design.  Only 3 have reported in the last 24 hours.

**Comment by davroth** [comment]
fair enough - but the picture above shows time filter set to 30 days and the summary cell still shows 3 devices
