### ISSUE TITLE
Sempra Summary grid - not refreshing when Listener shows messages coming in

### ISSUE THREAD

**Issue by davroth** [patrickomni/omnimobileserver#263]
1. Browse to https://nettelpong.azurewebsites.net/sv, FireFox 38, Windows 8.1, login as Dave, select Sempra
2. Observe Summary grid - most recent report if from Gateway 4, 07/21 at 5:04 PM
3. Open Listener log on VM (see below for instructions) and scroll to bottom
4. Observe most recent entry for TrapListener is 7/22 @ 19:52 GMT (offset by ~10 hrs from Hawaii, so that would be approx. 09:52 Hawaii time on 7/22)

Expected - Summary grid to display more recent entry

2015-07-22 19:52:46,928 [8] INFO  TrapListener.TrapListenerServer [(null)] - Inserted 1 Row(s)

VM: 'omni-m866yiw8.cloudapp.net'
 Username: 'omniadmin'
 Password: 'C1234i2i'

Open Windows Exporer.

Navigate to: 'C:\Program Files\OmniM2m\OmniListenerService', select file for 07/22 and open

**Comment by patrickomni** [comment]
This is because the trap inside the gateway in the office was registered as the same as Sempra's 5, which should have been Sempra's 4.   

Another live mess.
