### ISSUE TITLE
Alert not being sent when fuel level violates rule

### ISSUE THREAD

**Issue by davroth** [patrickomni/omnimobileserver#264]
From Frank's email for repro steps w/ screenshot below:
![capture - alert not sent](https://cloud.githubusercontent.com/assets/12534533/8859981/95f783c4-3135-11e5-8a9a-91d89ddd6afb.PNG)

I set up the "In Office" tank test device.

I adjusted the voltage (fuel level) so that it was more than half full and ensured that it was reporting. I changed the reporting interval to every 10 minutes so it is easier to track.

I then set the voltage (fuel level) to less than 50% full.

I changed the graph from 24 Hours to 3 Days to force a refresh and the data was correctly displayed in the graph.

However, the grid did not update and still showed the previous higher "Gallons Remaining". Also, the Percentage is missing, only displaying a dash ("-").

I set the voltage to a very low value and repeated the refresh. Again the graph refreshed but the grid did not. A page refresh remedied that and the grid not matches the graph in terms of Gallons Remaining. However, the Percentage is still missing.

Perhaps more disturbingly, the alert was not sent to my phone. The Site Rule is set to 22% and the Device Rule is set to 50%. At this point, either setting should have fired an alert. Neither did and there are no Alerts in the Active Alerts grid.

I really can't explain what is going on but I suspect it is tied to the fact that the Percentage field on the left Grid is missing but that is a guess

**Comment by patrickomni** [comment]
This was an issue of "Lack of Device Managment" :) 

When I inserted the row for Frank's device, I accidentally configured it for refrigreation.   Now it should both work, and whoever was signed up an SMS should have gotten an SMS
