### ISSUE TITLE
Alert - row entered in table each time a fuel device reading is below threshold

### ISSUE THREAD

**Issue by davroth** [patrickomni/omnimobileserver#266]
Frank configured a fuel device sensor registered in the Test Tanks account to report every 10 minutes and set a device level rule to create an alert if the level is below 50%.

Expected: a single alert in Active Alerts table along w/ a single SMS msg sent to all configured users (one of whom is Frank)

Actual: an entry in Active Alert table for the device every 10 minutes, many text messages sent to Frank

![capture - many alerts](https://cloud.githubusercontent.com/assets/12534533/8879690/d9b22594-31e7-11e5-8014-44a589a58a9b.PNG)

**Comment by patrickomni** [comment]
This was fixed on Friday.
