### ISSUE TITLE
Tank reading is not accurate

### ISSUE THREAD

**Issue by CaseyDengler** [patrickomni/omnimobileserver#27]

**Comment by patrickomni** [comment]
I made this update to this.   In a few hours compare this tank reading to the one on http://nettelpong.azurewebsites.net

**Comment by CaseyDengler** [comment]
Missed the few hours mark (my bad) but the reading still doesn't seem to accurate on http://omnistaging.azurewebsites.net/sv (unless it's been on 7439 gallons for 10 hours now) and the link provided, http://nettelpong.azurewebsites.net, doesn't have any information on the graph, and the number of gallons doesn't match up (#1 has 675 while #2 has 8346).

**Comment by CaseyDengler** [comment]
Data still seems a bit off, as the http://omnistaging.azurewebsites.net/sv data shows that there are only 6 gallons left in the tank (a sudden drop of 7000 gallons in 30min, unlikely). If the http://nettelpong.azurewebsites.net/ data is still supposed to be similar, if so, then the numbers have not changed since my last comment (Tank 1 with 675 and Tank 2 with 8346), though I doubt that they are supposed to be.

**Comment by patrickomni** [comment]
You are correct!   You are comparing against the right site, so if they are not equal, we are not done fixing this bug.  However, i found my goof; in the next set of readings that look reasonable should be accurate.

**Comment by CaseyDengler** [comment]
My fault, I was looking at the wrong page. While I don't know if the tanks were correct earlier, it's irrelevant as the tank data is now accurate.
