### ISSUE TITLE
Unknown editable box in top left of details page

### ISSUE THREAD

**Issue by CaseyDengler** [patrickomni/omnimobileserver#28]
Reproduce:
1) Log into Omni
2) Impersonate Reisner, Sempra, or Refrigeration

Expected:
Apparently the box is supposed to allow the user to edit the naming of the table's columns

Occurs:
It's just a box that the user can type in. Attempting to double click one of the table's names (messages, alerts, ect) causes the box to shrink. 
![odd text box](https://cloud.githubusercontent.com/assets/12438510/7625160/e3903a82-f9a8-11e4-954c-c30ab6566680.png)

**Comment by patrickomni** [comment]
that thing thar, has been removed :)
