### ISSUE TITLE
Report - name worksheets appropriately

### ISSUE THREAD

**Issue by davroth** [patrickomni/omnimobileserver#281]
When creating a device report activity report, the worksheets are currently named "Table 1" and "Table 2".

Table 1 should be renamed to "Device Report"
Table 2 should be renamed to "Alert Report"

**Comment by davroth** [comment]
Spreadsheet names <AccountName><TimeFilter>.xslx

Work sheet names:
Table - Last Reports
Table 1 - All Reports

**Comment by peters95** [comment]
+1

**Comment by peters95** [comment]
this is now fixed

**Comment by davroth** [comment]
Work sheet names:
First tab - change to 'Last Reports' from 'Device Report'
Second tab  - change to 'All Reports' from 'Alert Reprt'

**Comment by peters95** [comment]
hey dave can you scan thru the rest of the defects please and make all these kind of updates before I get to them? it would really help me out to prevent rework. this has been changed now. thanks!
