### ISSUE TITLE
Fridge Sensor Property Report details

### ISSUE THREAD

**Issue by davroth** [patrickomni/omnimobileserver#288]
The purpose of this report is to display each individual device report in an excel spreadsheet.
1. All data in the spreadsheet will be represented in a format that allows direct manipulation. The spreadsheet be sortable in an expected manner by any property. For example, Temp will be sortable in either an ascending or descending order based on that sensor property reading. Similarly, the Time property will be sortable. 

2.It will be possible to highlight an area in the report and create an excel graph.

3.Data will initially be displayed sorted by time, most recent report first.

4.Columns will be identical to those displayed in the "Last Report" (Summary) grid:
 a. Name - text field that is name of asset to which sensor is attached
 b. Voltage - numeric value representing the voltage level reported
 c. Temp - numeric value representing the temperature reported (column header to include indicator whether it's Fahrenheit or Centigrade)
 d. Time - date/time value that is the time Omni received the report from the device

**Comment by davroth** [comment]
Changing columns to reflect possibility of "site"

4.Columns will be identical to those displayed in the "Last Report" (Summary) grid:
 a. Group - name of group to which device belongs
 b. Name - text field that is name of asset to which sensor is attached
 c. Voltage - numeric value representing the voltage level reported
 d. Temp - numeric value representing the temperature reported (column header to include indicator whether it's Fahrenheit or Centigrade)
 e. Time - date/time value that is the time Omni received the report from the device

**Comment by davroth** [comment]
Changing columns to reflect possibility of "site"

4.Columns will be identical to those displayed in the "Last Report" (Summary) grid:
 a. Group - name of group to which device belongs
 b. Name - text field that is name of asset to which sensor is attached
 c. Voltage - numeric value representing the raw voltage level reported
 d. Temp - numeric value representing the temperature reported (column header to include indicator whether it's Fahrenheit or Centigrade)
 e. Signal strength - raw value
 f. Time - date/time value that is the time Omni received the report from the device

**Comment by peters95** [comment]
+1

**Comment by peters95** [comment]
The report already shows all this.. the only contentious column is "battery left" vs "voltage". closing this item now.
