### ISSUE TITLE
Freezer default temp range needs to be -10 F .. 1 F

### ISSUE THREAD

**Issue by davroth** [patrickomni/omnimobileserver#290]
Current default is -20 .. 0; please change to -10 F .. 1 F

According to the FDA, a freezer should always be set at 0 degrees Fahrenheit or below

Read more : http://www.ehow.com/facts_7488829_fda-food-storage-temperature-guidelines.html

**Comment by christopherdude** [comment]
Fixed in changeset 899... however the quick fix (if you don't want to get all of the new stuff and introduce problems is to change this line below in ModalRulesSettings.ascx (NOT the C# file)

```
function SetDefaultsFreezer()
{
    SliderSetRange(-10, 1);   <---- I changed to this, but you can change in the existing
}
```
