### ISSUE TITLE
Norm's devices - date time displaying in Last Report grid is incorrect

### ISSUE THREAD

**Issue by davroth** [patrickomni/omnimobileserver#291]
Date/time stamp of reports in Last Report (Summary) grid is reading 6+ hours ahead of Pacific Daylight Time, likely on Universal (Greenwich) Time. Please ensure that lat/lon for all Norm's devices is correctly set as below.

Note - time in Last Report grid is identical to the time written by the Listener to its logs. Lat/lon does not appear to be reported by these devices, so we need something in our db.

Latitude – 47 40’ 24”
Longitude – 122 20’ 33”

**Comment by peters95** [comment]
hey I assigned this lat / long a while back here is the data from DeviceInventory..

AccountId   Name    DeviceTypeId    SiteID  LastKnownGeoLoc DevicePassword  DeploymentScenarioId    CustomerUnitNumber
1271    TBD 6   169 47.4024,-122.2033   NULL    4   Norms 1
1271    TBD 5   169 47.4024,-122.2033   NULL    4   Norms 2
1271    TBD 6   169 47.4024,-122.2033   NULL    4   Norms 3
1271    TBD 6   169 47.4024,-122.2033   NULL    4   Norms 4
1271    TBD 6   169 47.4024,-122.2033   NULL    4   Norms 5
1271    TBD 6   169 47.4024,-122.2033   NULL    4   Norms 6
1271    TBD 6   169 47.4024,-122.2033   NULL    4   Norms 7
1271    TBD 6   169 47.4024,-122.2033   NULL    4   Norms 9
1271    TBD 6   169 47.4024,-122.2033   NULL    4   Norms 10
1271    TBD 6   169 47.4024,-122.2033   NULL    4   Norms 8

I probably missed something else somewhere though if this is still an issue

**Comment by patrickomni** [comment]
I noticed that the DeviceTypeId for norms was 6, which is my best first guess on the issue.  I made the edito to make them 5 (which they should have been).  We should know on the next time a report comes in.   If you want me to also fix history update this bug and resend
