### ISSUE TITLE
Rules dialog - "please wait" message does not clear itself after saving rule

### ISSUE THREAD

**Issue by davroth** [patrickomni/omnimobileserver#292]
1. Browse to https://omnim2m.net/sv, Chrome 43, Windows 8.1, login as Dave R, select Dave's Sushi
2. Click global rule and make change
3. Click save

Expected - rule to be saved, and control returned

Actual - "please wait" message remains on screen until screen refresh button is clicked. When you return to the global rule, your changes will have been saved.

![capture - please wait](https://cloud.githubusercontent.com/assets/12534533/9446738/10653b76-4a48-11e5-9863-9dffe401e37f.PNG)

**Comment by christopherdude** [comment]
THis is fixed with changeset 865 from 7/23/2015

**Comment by davroth** [comment]
See 296 for information - problem appears to be caused by same error: "TypeError: Cannot read property 'PRM_ParserErrorDetails' of undefined"
