### ISSUE TITLE
Norm's - create 2 device groups to separate freezer from fridge devices

### ISSUE THREAD

**Issue by davroth** [patrickomni/omnimobileserver#294]
If possible, make this change to production system data for Norm's account devices.

Today, graphing the 8 devices from Norm's that are reporting results in a temperature spread of 80 degrees. This makes it very difficult to see temperature fluctuations in individual devices. Even removing the one outlier device (Norm's 9) that is reporting temp's in the 70's, we still see a temperature range of nearly 50 degrees. While it is possible to de-select individual devices, it would be much more convenient if we could create 2 groups of devices to make it easier (more intuitive) to reduce the range displayed on a graph.

Freezer devices - Norms 3, Norms 6
Fridge devices - Norms 8, Norms 10, Norms 4, Norms 7, Norms 5

Norms 9 appears to not be in a cooler as it is sending temperatures in the 70's.

**Comment by patrickomni** [comment]
Done.  I put 1,2, 9 in "All Others"
