### ISSUE TITLE
Graph - change graph type to "scatter with markers"

### ISSUE THREAD

**Issue by davroth** [patrickomni/omnimobileserver#295]
This is a change request to be delivered for V1.2

Today, our graphs are scatter graphs that display as lines with "angles" where data points have been recorded. On a graph with a large range along the Y axis, it can be difficult to see where the actual angles are.

This change request is to modify the graph type to what Excel calls "Scatter with Markers" so there are indicators where the actual data points exist on the graph.

![capture - graph with markers](https://cloud.githubusercontent.com/assets/12534533/9479454/5e9acc76-4b32-11e5-9efa-7c712af344f0.PNG)

**Comment by christopherdude** [comment]
This has been fixed / changed back to showing points now
