### ISSUE TITLE
Seabend - time zone not displaying correctly

### ISSUE THREAD

**Issue by davroth** [patrickomni/omnimobileserver#297]
Please set Seabend devices to be same device type as Norm's (type 5?) and use the following lat/lon:

Lat - 47 degrees 44' 42"
Lon 122 degrees 21' 00"

We want time stamps on the Last Report (and Alert) grid to show up as PDT - these devices are in Seattle area (Shoreline)

**Comment by davroth** [comment]
Note - looking at Listener log, Seabend devices appear to be reporting lat/lon; so I don't know whether that makes a difference in "device type"

2015-08-26 20:20:26,039 [69] DEBUG SendumDevice.SendumDevice [(null)] - Lattitude: 8901093
2015-08-26 20:20:26,055 [69] DEBUG SendumDevice.SendumDevice [(null)] - Longitude: -22807128

**Comment by davroth** [comment]
924 N 165th St, Shoreline, WA 98133

**Comment by patrickomni** [comment]
fixed
