### ISSUE TITLE
NT-Employee - Omni Refrigeration / Fridge Sample

### ISSUE THREAD

**Issue by patrickomni** [patrickomni/omnimobileserver#3]
Under NT-Employee - Omni Refrigeration / Fridge Sample - Edit option for Omni Refrigeration / Fridge Sample is not working, after clicking the Edit option it is opening new div with Please wait... tittle and nothing is happening. 
![image](https://cloud.githubusercontent.com/assets/12114620/7517794/b461fde4-f4f4-11e4-8ac1-bde72fe513e6.png)

**Comment by patrickomni** [comment]
I think this has been fixed.  Can you verify?

**Comment by CaseyDengler** [comment]
Yep, it's been fixed already.
