### ISSUE TITLE
"Getting rules for item returned no results" comes up when trying to edit rules

### ISSUE THREAD

**Issue by CaseyDengler** [patrickomni/omnimobileserver#30]
Steps to reproduce (not entirely sure):
1) Log into Omni
2) Impersontate tanks, traps, or fridge
3) Attempt to change the rules (might have to change rules first, can't tell)

Occurs:
A pop-up informs the user that "Getting rules for item returned no results"
This error appeared to occur after rules where abolished, so perhaps the error is related

![getting rules](https://cloud.githubusercontent.com/assets/12438510/7625502/4f0b97d0-f9ad-11e4-91b3-029e4a1b3744.png)

**Comment by patrickomni** [comment]
Chris: We shouln't ever get this as at least I pull a default, but I may have damaged the data.  Either way, we should not show this message; keep there until we can find a repro.

Assigning back to Casey:  Casey, see if you can find more specific steps (it could have been tank specific or trap specifiic?

**Comment by patrickomni** [comment]
Oooh, I found it.  Let me see if its me.

**Comment by patrickomni** [comment]
Chris your get rules code is  not looking at all tables.  the result comes in the third table.

sp_GetRulesByDeviceOrSite 0,35,1

**Comment by CaseyDengler** [comment]
Error still around, just with a new box. This only seems to occur in Tanks when changing the rules for "Distributors" or "Cowden"

**Comment by christopherdude** [comment]
We've fixed this in 2 areas - Pat's fix on the 3rd table check, and my fix on a previous bug for checking for DeviceId = -1.  I don't see this happening anymore.

**Comment by CaseyDengler** [comment]
I'm not sure if this is the same issue.
![getting rules box](https://cloud.githubusercontent.com/assets/12438510/7712642/42f9fdd2-fe27-11e4-9904-0b72557f7b8e.png)
If not, then feel free to close it, but I think I'm going to make a separate issue involving this box because it's involved in many issues so far.

Aside from that, the older red box hasn't shown up at all.

**Comment by CaseyDengler** [comment]
Only occurred once before changing the rules, as it seems should happen. Fixed.
