### ISSUE TITLE
Management - change name on title bar to "Account Management"

### ISSUE THREAD

**Issue by davroth** [patrickomni/omnimobileserver#305]
The current title bar is Add Account, even when Devices tab is selected. I think a more encompassing title would be "Account Management"

**Comment by davroth** [comment]
![capture - account management](https://cloud.githubusercontent.com/assets/12534533/9595744/393b0102-501f-11e5-9f68-79f5332d9e50.PNG)

**Comment by peters95** [comment]
+1

**Comment by peters95** [comment]
this is now fixed.
