### ISSUE TITLE
Last Report (Summary) grid - voltage column should be "mAH left"

### ISSUE THREAD

**Issue by davroth** [patrickomni/omnimobileserver#306]
Today, our Last Report (Summary) grid shows a column heading of voltage. However, the column itself, for tanks, fridge is reporting milli amp hours. 

Since milli amp hours is more precise than voltage, I would like to do the following for fridge and tank:
1. change column heading to "mAH left" or simply "mAH" if there's a real estate issue

I will ask Gary/JohnS whether we should change Sempra's report so that it shows mAH , so unless there's an update below, leave Sempra as is (column heading accurately reflects column data)

**Comment by peters95** [comment]
+1
