### ISSUE TITLE
Fridge sensor property report changes needed

### ISSUE THREAD

**Issue by davroth** [patrickomni/omnimobileserver#309]
1. browse to omnistaging.azurewebsites.net/emp, chrome 43, windows 8.1, select Test Fridge
2. Set time filter to Last 30 days, observe many data points on scatter graph
3. Click report icon at top of summary grid

Actual - report created w/ last report for each device and columns for a) site b) unit c) temperature d) signal strength e) battery level f) location g) date

Expected - report created w/ last 30 days of reports and columns as specified in #288: 
 a. Name - text field that is name of asset to which sensor is attached
 b. Voltage - numeric value representing the voltage level reported
 c. Temp - numeric value representing the temperature reported (column header to include indicator whether it's Fahrenheit or Centigrade)
 d. Time - date/time value that is the time Omni received the report from the device

![capture - fridge report](https://cloud.githubusercontent.com/assets/12534533/9796519/71747ee8-57ab-11e5-99a1-3aa00410d76b.PNG)

**Comment by peters95** [comment]
+1

**Comment by peters95** [comment]
this is fixed columns now match name, voltage, temp, and time.
