### ISSUE TITLE
When attempting to save new rules "Error saving rules: Input string was not in a correct format" pops up

### ISSUE THREAD

**Issue by CaseyDengler** [patrickomni/omnimobileserver#31]
Steps to reproduce:
1) Log into Omni
2) Impersonate tanks, traps, or fridge
3) Open rules
4) Change the rules
5) Click "Save Rule"

Expected:
"Rules saved" or something of the sort should pop up in a green box

Occurs:
A red text box comes up saying "Error saving rules: Input string was not in a correct format"

**Comment by patrickomni** [comment]
Cannot reproduce.   This may have been fixed already.  Assigning to chris first for check.

Chris-> we need to wire the new Formatters function  for validating this as well as the phone number when setting up a user.   See Formatters.FormatPhoneNumbers and Formatters.FormatPhoneNumber

**Comment by christopherdude** [comment]
Yes, I fixed this one a few days ago.  The issue was trying to convert a "" to an int.  It's been fixed.  I just checked it again, and it seems to work.

**Comment by CaseyDengler** [comment]
The red box is gone. There are still errors in trying to save the rules themselves, but those are in different issues already, so I'll close this up.
