### ISSUE TITLE
Staging site - add Sea Bend Meats and Norms accounts

### ISSUE THREAD

**Issue by davroth** [patrickomni/omnimobileserver#311]
Need data from these accounts to exercise functionality for fridge scenario - groups, reports, alerts

**Comment by peters95** [comment]
+1 ... Are we ok with replacing staging data with production data??

**Comment by davroth** [comment]
First, note change in accounts to Daves Sushi and Sea Bend - Norm's has been inactive for over a month (dead batteries) 

Yes - carefully of course (don't want to do it backwards!)
1. Remove all data in STAGING from Daves Sushi and Sea Bend
2. Copy all data from PROD for Daves Sushi and Sea Bend
3. Insert copied data into STAGING
