### ISSUE TITLE
Alerts - low battery alert not being sent

### ISSUE THREAD

**Issue by davroth** [patrickomni/omnimobileserver#316]
Pearl's Sendum device (id 05671343) delivered a LOWBATTERYCAP alarm to Classic Omni Listener on 2015-09-20 11:42:04 GMT (see below). When looking at the portal on 2015-09-21 @ 11:20 PDT (18:20 GMT), filter was set to "last 3 days" to ensure the alert would be included and there are no active alerts displayed.

I don't know whether/how Sendum alarm messages are processed - do they result in Omni alerts or do we ignore them and look at our own rules?

**Comment by peters95** [comment]
Is LOWBATTERYCAP different than a low voltage reading?

**Comment by davroth** [comment]
we are only processing status reports from Sendum devices now; other types of messages are only being written to DeviceMessages, an unused table
