### ISSUE TITLE
Landing Page - include Account Name on title bar

### ISSUE THREAD

**Issue by davroth** [patrickomni/omnimobileserver#318]
Please add the Account Name to the Landing Page Title bar - prefer that the Account Name be above where the name of the logged in user currently is - we'd have 2 lines there (left aligned):

<Account Name>
<Logged in User>

If that is too difficult, then there's a large space between the Omni logo and the User Guides link - place the Account Name between those in vertical alignment w/ User Guides

**Comment by peters95** [comment]
can you send me a wireframe?

**Comment by davroth** [comment]
![capture - account name](https://cloud.githubusercontent.com/assets/12534533/10801316/0dcf225a-7d74-11e5-8247-6d5ef6fc5f2a.PNG)

**Comment by peters95** [comment]
propped change to omnistaging this is fixed
