### ISSUE TITLE
Saving the Y-Hata fridge slider affects Boat #1, Boat #2, and all individual devices

### ISSUE THREAD

**Issue by CaseyDengler** [patrickomni/omnimobileserver#32]
Steps:
1) Log into Omni
2) Impersonate fridge
3) Open the rules for Boat 1, Boat 2, or an individual device
4) Change the slider rules
5) Click on "Save rules"
6) Open the rules for Y-Hata
7) Change the slider rules for Y-Hata
8) Click on "Save rule"
9) Open the rules for Boat 1, Boat 2, or an individual device

Occurred:
The changes that happened to the Y-Hata rules affected the rules that were lower down on the list, changing their rules.

Expected:
Rules that were created for the sub categories or the individual devices shouldn't be changed if the user made specific rules to that sub category or device when changing the universal rules

**Comment by patrickomni** [comment]
I cannot  reproduce this item.

**Comment by patrickomni** [comment]
Didn't know that would close it.  Close it if you cannot repro

**Comment by CaseyDengler** [comment]
I cannot reproduce it exactly, but after messing around with the sliders a few times, both Y-Hata and Boat 2 seem to resist changing from (74F to 92F). The individual devices stuck to their own rules and Boat 1 (which was not messed with) did not force itself to the same 74 to 92 rule. I'll log a bug for this issue and close the current bug.
