### ISSUE TITLE
Limelight catering - change 2 devices to PT 300 Advanced (device type 6) after #323 is fixed

### ISSUE THREAD

**Issue by davroth** [patrickomni/omnimobileserver#324]
A bug in setting the timezone offset bypasses timezone adjustment for PT 300 Advanced devices.  When #323 is fixed, this bug should also be fixed and the Limelight devices set back to PT 300 Advanced (device type 6)

Device id's - 05671501, 05672080

**Comment by peters95** [comment]
complete on OmniPing now
