### ISSUE TITLE
Account mgmt - adding new user w/ 3 'names' trims 3rd 'name'

### ISSUE THREAD

**Issue by davroth** [patrickomni/omnimobileserver#327]
Windows 10, Chrome 43
1. Browse to https://omnistaging.azurewebsites.net/emp, log in as dave@omnim2m.com, click +Account Management
2. Click Users button adjacent to Account Name 1, click Add New Users button
3. Enter Marie Van Zandt for Name, select Site Administrator, enter 0123456789 for phone, enter marie@sempra.com for email
4. click Save

Expected - name to be Marie Van Zandt

Actual - name is Marie Van

Please add a First Name and a Last Name box to the dialog

**Comment by peters95** [comment]
ok i will add last name dialog

**Comment by peters95** [comment]
fixed live on omnistaging w/ first & last name boxes
