### ISSUE TITLE
User Management - no way to reset password

### ISSUE THREAD

**Issue by davroth** [patrickomni/omnimobileserver#328]
Windows 10, Chrome 43
1. Browse to https://omnistaging.azurewebsites.net/emp, log in as dave@omnim2m.com, click +Account Management
2. Click Users button adjacent to Account Name 1

Expected - some way to reset password for user

Actual - no way to do that

Before fixing, we need to discuss design issues given our non-tech savy user base

**Comment by peters95** [comment]
Dave, any update or insert into user will now trigger a text to the user phone and they have to use our new Reset Password page which now exists for them to redo their password.
