### ISSUE TITLE
Account Management - add Account Name to title bar of all edit pages

### ISSUE THREAD

**Issue by davroth** [patrickomni/omnimobileserver#329]
Windows 10, Chrome 43
1. Browse to https://omnistaging.azurewebsites.net/emp, log in as dave@omnim2m.com, click +Account Management
2. Click Users button adjacent to Account Name 1

Expected - some indication on screen that comes up i'm editing users in Account Name 1

Actual - list of users comes up but there's no indication of account name

this is particularly important for busy Omni employees so they can be certain which account they're editing; makes testing a lot easier too

**Comment by peters95** [comment]
ok i will add a h2 w/ account name at top of every page except Account List.

**Comment by peters95** [comment]
live on omnistaging
