### ISSUE TITLE
Reports - no results on 'All Reports' tab when running report for Sempra

### ISSUE THREAD

**Issue by davroth** [patrickomni/omnimobileserver#333]
https://omnistaging.azurewebsites.net/sv, windows 10, chrome browser, logged in as dave@omnim2m.com, selected Sempra landing page and ran reports w/ device filter set to 'Stations' (all devices) and Time filter set to Last 24 hrs. I opened the report and went to the All Reports tab

Expected - see a large number of device reports

Actual - no data on page

This bug also exists in prod; related to #284
![capture - reports no data](https://cloud.githubusercontent.com/assets/12534533/10805122/c8a08efc-7d88-11e5-9714-deb6213f439e.PNG)

**Comment by peters95** [comment]
The second page is incorrectly labeled. it is showing the alerts. Since there was no alerts in the last 24 hours this data sheet is empty. I will rename column to Active Alerts and close.
