### ISSUE TITLE
Need to remove resource changing (double-click) on login screen

### ISSUE THREAD

**Issue by patrickomni** [patrickomni/omnimobileserver#35]

**Comment by CaseyDengler** [comment]
For clarification,

Steps:
1. Go to the Omni Log in screen
2. Hover over "Sign in" or "Sign in using your registered account"

Expected:
Nothing

Occurs:
A small box comes up saying "Double click to change label" which is the same that comes up when changing the data table's labels. They can't actually be changed, but the box still comes up.

**Comment by patrickomni** [comment]
Just disable resource changing on   emp and login

**Comment by christopherdude** [comment]
I made the change on login, but didn't see where it existed on EMP page?

**Comment by CaseyDengler** [comment]
My bad, I can't find it on the EMP page either.
