### ISSUE TITLE
NT - Scenario View - Graph Display & Refresh

### ISSUE THREAD

**Issue by patrickomni** [patrickomni/omnimobileserver#37]
Signed in without credentials, selected "Reisner Distributor, Inc / Reisner Client", Device Details are not showing a graph for 24 Hrs; displays, after refreshing, only when "3 days" is selected from drop down, but displaying last 24 Hrs. If "Last 30 days" is selected, the display, after refreshing is displaying data for 30 days.

If "Live data" is selected it reports, after refreshing, refreshing every 5 secs, but says no Data to Display (No Data for the item selected"  (which may be true), but the Screen is not refreshed to blank, still displaying "Last 30 day" data.

Same if we again select "Last 24 Hrs"

**Comment by patrickomni** [comment]
When there is no data to display, instead of showing the warning pop-up, let's replace the spinner with "No Data to Show for this time Period"

**Comment by christopherdengler** [comment]
This is now fixed!

**Comment by patrickomni** [comment]
Reopening

**Comment by christopherdude** [comment]
Fixed, ready for test

**Comment by CaseyDengler** [comment]
Closing, everything seems fine.
