### ISSUE TITLE
Attempting to save rules for Tanks hangs the page

### ISSUE THREAD

**Issue by CaseyDengler** [patrickomni/omnimobileserver#38]
Steps:
1) Log into Omni
2) Impersonate Tanks
3) Go into the rules for Distributors or for the specific device
4) Click on "Save rules" (you can change rules if you want, same effect occurs)

Occurs:
The "Please Wait..." pop up bar shows up and just stays there forever. The user must refresh the page in order to break out of the wait. Obviously, no rules are changed after.

Also, this old pop up shows up:
![getting rules box](https://cloud.githubusercontent.com/assets/12438510/7712557/db228dd2-fe26-11e4-89d5-84cc99a9b643.png)
This seems to be related to some other problems so far

Expected:
The page saves any rules that are made and the "Please Wait..." sign is only up for a limited time.

**Comment by christopherdude** [comment]
Fixed.  This was an error in JS logic.

**Comment by CaseyDengler** [comment]
Still able to reproduce, but only when no rules are changed.

I did run into a few times when the "Please Wait" went on for a while after changing the rules, but after refreshing the rules did change. I'm not sure if it did hang or if it was just taking a long while to work in these cases.

**Comment by patrickomni** [comment]
Works for individual, but not for site

**Comment by patrickomni** [comment]
Fixed
