### ISSUE TITLE
"Getting rules for this item returned no results" pop up is related to many issues

### ISSUE THREAD

**Issue by CaseyDengler** [patrickomni/omnimobileserver#39]
Steps:
1) Log into Omni
2) Go to Tanks (or device FR144 and FRZ55 in Boat 2 under Y-Hata for the fridge section)
3) Open up the rules

Expected:
Not really sure. I assume that this is supposed to show up if no one has set any rules what so ever, but even after changing rules, this pop up comes along and the previously changed rules are set back to what they were before any changes.

I'm not sure if the rules are being ignored, changed back to defaults, or are being changed at all.

Occurs:
This guy
![getting rules box](https://cloud.githubusercontent.com/assets/12438510/7712779/45279bf4-fe28-11e4-9755-f494c7f79f18.png)
Likes to hang out around my comments. Not a fan of him personally. Any rules that the user attempts to change are ignored and the defaults are reset when opening up the rules again.
Also he shows up again. Still bringing nothing to the party.

**Comment by christopherdude** [comment]
This is not good.  I am seeing the rules being saved at line 174 of ModalRulesSettings.ascx.cs file.  Pat, can you debug to see if the fields are correctly going in?

**Comment by patrickomni** [comment]
Fixed

**Comment by CaseyDengler** [comment]
Can't reproduce.
