### ISSUE TITLE
Traps Device Data UI is a bit odd

### ISSUE THREAD

**Issue by CaseyDengler** [patrickomni/omnimobileserver#40]
Steps:
1) Log into Omni
2) Go to Traps
3) Look at the "Device Data" on the right

Occurs:
![trap device data](https://cloud.githubusercontent.com/assets/12438510/7713116/87ab609e-fe2a-11e4-8de5-a5299e23308e.png)

Few questions arise:
- What is "Type" and "Status?"
- Should the names on this table be subject to change by double clicking on them (as of now they cannot be changed)?
- Which trap was armed?

There's also a fair amount of white space on the top and left part of the table, which make it look a bit off. The table (I think at least?) should be clipped to the top left of the window in Device Data.

**Comment by patrickomni** [comment]
Clean up borders if possible but otherwise move to milestone "future"

**Comment by christopherdude** [comment]
This is more of a database thing than me?

**Comment by patrickomni** [comment]
I fixed this I hope
