### ISSUE TITLE
Map in Traps looks off

### ISSUE THREAD

**Issue by CaseyDengler** [patrickomni/omnimobileserver#41]
Steps:
1) Log into Omni
2) Go to Traps
3) Click on the right arrow below "Device Data" found on the right of the screen

Expected:
Map shows up giving the user locations to the different traps

Occurs:
The traps appear to be in the ocean. Unless they are on tiny islands or are underwater traps, I'm not sure why they are there.
![trap map](https://cloud.githubusercontent.com/assets/12438510/7713268/75ff732a-fe2b-11e4-9979-e6c8d51cc907.png)

**Comment by patrickomni** [comment]
This is just where they are in the database as I noted.
