### ISSUE TITLE
Device Data not showing up for Traps after switching from Stations in the drop box

### ISSUE THREAD

**Issue by CaseyDengler** [patrickomni/omnimobileserver#42]
Steps:
1) Log into Omni
2) Go to Traps
3) Click on the drop box in the top right of the page (where it says Stations)
4) Select any of the sub station numbers (1 is recommended as it shows that the Device Data doesn't show up on it)
5) Go back to Stations

Expected:
The data that's shown is similar or identical to the data shown when the page started up. The Device Data is visable.

Occurs:
The Device Data disappears, showing a blank box
![trap 1 device data blank](https://cloud.githubusercontent.com/assets/12438510/7713463/bd3173e6-fe2c-11e4-9be7-8d6f9de7dda9.png)
The map still works fine though.

Note, this could possibly be related to why the other stations (really 1 as it's the only one with data) aren't showing up with anything for Device Data either.

**Comment by patrickomni** [comment]
This is by design in that there really isn't much data there.  

However there should be "No Device Data " message so I am sending to Chris.

**Comment by christopherdude** [comment]
I believe this was fixed with a previous, but similar issue on another page.  Please verify if it works now.  I went through it and saw data on each page.

**Comment by CaseyDengler** [comment]
Yep, fixed up.
