### ISSUE TITLE
Going to omnistaging.azurewebsites.net after closing the page without logging out brings user to a blank page

### ISSUE THREAD

**Issue by CaseyDengler** [patrickomni/omnimobileserver#44]
Steps:
1) Log into Omni
2) Close the page or tab
3) Go straight to omnistaging.azurewebsites.net

Expected:
Either the site forces the user to sign in or acts like they never left

Occurs:
The site is almost blank, except for a few details
![almost blank page](https://cloud.githubusercontent.com/assets/12438510/7714454/7b62a28a-fe33-11e4-8f97-452389f64ff3.png)

**Comment by christopherdude** [comment]
Fixed in next build for test
