### ISSUE TITLE
NT - Scenario View - Tanker Refill Indicator

### ISSUE THREAD

**Issue by Rahul-Silicon** [patrickomni/omnimobileserver#46]
In Reisner Client, the Tanker Refill Indictor is showing properly upon load

![image](https://cloud.githubusercontent.com/assets/12525836/7723441/37fd1100-ff06-11e4-9d33-a5feccf0a90c.png)

However, this Refill Indicator is disappearing when I select Distributor Cowden. The Graph is NOT displaying upon refresh. I should mention, I am using an XP version, Google Chrome. (This is visible on other machines, so I am not sure if it is my system issues). I have cleared my cache and tried also.

![image](https://cloud.githubusercontent.com/assets/12525836/7723527/0b3b761a-ff07-11e4-9536-473fe8b4db26.png)

**Comment by patrickomni** [comment]
Google on XP is not supported; there are too many issues with HTML5.

**Comment by Rahul-Silicon** [comment]
In iPad safari browser also same issue.
