### ISSUE TITLE
Addnewaccount window is not closing automatically after creating the account.

### ISSUE THREAD

**Issue by Rahul-Silicon** [patrickomni/omnimobileserver#47]
Steps to reproduce:
1. Sign in without credentials.
2. Add new account and fill the Account Name and select the scenario type from the drop down and hit the Save button. It will show popup message that account saved but  after saving the account, open window is not closing automatically.

Expected : After  adding the Add new account and hitting save button, window should close automatically .

Adding new account with confirmation account is saved.
![add account](https://cloud.githubusercontent.com/assets/12525836/7726860/8a5d0754-ff22-11e4-8048-800d590aa89f.png)

**Comment by patrickomni** [comment]
By design.
