### ISSUE TITLE
Add user inputs fields are not getting cleared or resets blank.

### ISSUE THREAD

**Issue by Rahul-Silicon** [patrickomni/omnimobileserver#49]
Steps to reproduce:
1. Signin without credentials
2. Select any type account to Edit the properties of the account and add new user for the account.
3. Click save user.

Expected : 1)  It should allow user to save new user for the account but here user is not saving when you click on the save user button.

2) If you click cancel button, without saving the user and close the window and  if again you will open edit window for other account and go to user section, here input fields are not getting blank or resets. Previous users input data is remain as it is in the input fields.

![add user](https://cloud.githubusercontent.com/assets/12525836/7727639/b2a318e8-ff27-11e4-9188-85243c77cc78.png)

**Comment by patrickomni** [comment]
I think this is a duplicate.  Casey, please check to see if it is already logged.

**Comment by CaseyDengler** [comment]
Although there are issues that are related to this one, there aren't any (aside from this one) I could find that address the issue of the user information carrying over from one account to another.

**Comment by DaveRoth** [comment]
STOP THIS FEED / REMOVE MY EMAIL

Dave Roth

**Comment by CaseyDengler** [comment]
Similar to #57 but newer bug seems to have additional info. I'll close this but copy the information into a  comment for #57.
