### ISSUE TITLE
In Rules Setting page selected user is not listing in text box.

### ISSUE THREAD

**Issue by Rahul-Silicon** [patrickomni/omnimobileserver#50]
Step to reproduce:

Signed in without credentials, select  "Sempra Energy / Marie Van Zandt" and Select settings for devices and select (check the user) from check box it should list the user in text box. But in current system selected user is not listing and showing in the textbox.

![usernotify](https://cloud.githubusercontent.com/assets/12525836/7728054/84320156-ff2a-11e4-8cf2-14601963acb9.png)

,

**Comment by patrickomni** [comment]
We simply need to remove the grey highlighted box that isn't used anymore

**Comment by christopherdude** [comment]
Done

**Comment by CaseyDengler** [comment]
Assuming that I'm getting this right, I'm still able to reproduce.
![something in the way](https://cloud.githubusercontent.com/assets/12438510/7763954/a14123f2-fffd-11e4-88c0-90671efbad80.png)

**Comment by patrickomni** [comment]
fixed again
