### ISSUE TITLE
Table formatting and allignment issue

### ISSUE THREAD

**Issue by Rahul-Silicon** [patrickomni/omnimobileserver#51]
Steps to reproduce:
1. Use Mozilla Firefox browser

Signed in without credentials, select "Sempra Energy / Marie Van Zandt" It will redirect you to Scenario view page of  Sempra Energy . In this page do Zoom in Zoom out and analyze the page at 120 % table formatting for Latest Report will not align properly.

![allignment](https://cloud.githubusercontent.com/assets/12525836/7728331/44238a7e-ff2c-11e4-879c-0a3cb3772d0d.png)

**Comment by patrickomni** [comment]
This is a duplicate
