### ISSUE TITLE
Login without Authorization

### ISSUE THREAD

**Issue by Rahul-Silicon** [patrickomni/omnimobileserver#54]
Steps to reproduce:
1. Open http://omnistaging.azurewebsites.net login page.
2. Enter single Space character in user name and in password fields.
3. Click login button.
4. It will allow user to login as blank account name.

Expected: It should not allow user to login into the website, because any unauthorized user can modify data or account type.

![login](https://cloud.githubusercontent.com/assets/12525836/7730833/29f94a22-ff3a-11e4-9fb9-d350403ab102.png)

**Comment by patrickomni** [comment]
This is a #DEBUG option that won't be deployed in retail.
