### ISSUE TITLE
No way to identify which trap device has sent displayed message when all Stations selected

### ISSUE THREAD

**Issue by davroth** [patrickomni/omnimobileserver#55]
Device data box has message indicating 
1. log on to http://omnistaging.azurewebsites.net/emp as Patrick
2. select Sempra Energy scenario
3. Observe displayed page -  
   a. devices from all stations are displayed. "Latest Report" shows latest report data for 9 devices and
       all devices are selected
   b. device data box on right side of screen has 1 message - "trap has been armed"

Expected - some way to identify the device from which the message in the data box was sent

Actual - column data for Message, Type, Status, Date but there is no way to know which of the devices reported that a trap has been armed
![capture-devicedata](https://cloud.githubusercontent.com/assets/12534533/7737181/0f5c4340-fefe-11e4-9dbb-f52b80ea6708.PNG)

**Comment by patrickomni** [comment]
It now includes device, but before logging more bugs on alerts data bugs, email me first.  Some of those alerts are test data and I'm building up real alerts through the test harness.
