### ISSUE TITLE
Saving rules taking longer than 2 minutes

### ISSUE THREAD

**Issue by davroth** [patrickomni/omnimobileserver#56]
Trying to save a new rule does not ever return control to the user
1. Log onto http://omnistaging.azurewebsites.net as Patrick (using IE as browser)
2. Select Reisner scenario
3. After screen is displayed, click the Settings icon
4. In window that pops up, select Reisner client, then click "Save rule"
5. Observe popup saying "Please wait"

Expected - save action completes

Actual - work never seems to complete; buttons are all disabled, so the only choices are to close the tab or hit the browser's back button Note highlighted timestamps in lower left of 2 screenshots attached.

![capture-rulenotsaved](https://cloud.githubusercontent.com/assets/12534533/7737642/59a35792-ff01-11e4-8c3d-f0367a91c918.PNG)
![capture-rulenotsaved2](https://cloud.githubusercontent.com/assets/12534533/7737643/5c197240-ff01-11e4-8085-e93d80cdc5c8.PNG)

**Comment by davroth** [comment]
Duplicate of Issue 39

**Comment by DaveRoth** [comment]
Why am I receiving these emails?

Dave Roth

**Comment by davroth** [comment]
Hey Dave, Are you the same guy who used to get my email when we were at Msft?

I just got a Github acct today and used my old email alias. Looks like there's something about my Github registration that's unintentionally going to you rather than me.

Apologies for inconvenience while we get this fixed. Hope all going well for you

Dave Rothenberg

-----Original Message-----
