### ISSUE TITLE
Devices section when editing an account is always empty (Likely already known)

### ISSUE THREAD

**Issue by patrickomni** [patrickomni/omnimobileserver#6]
## It seems like this bug is already known, therefor the Severity will be low even though it would otherwise be high
1. Log onto http://omnistaging.azurewebsites.net/
2. Click on "Edit" for any of the editable accounts
#3. Go to the "Devices" tab

Occurs:
The "Devices" section holds no data in it, let alone anything that can be edited, besides informing the user that there is no data available, even though there are traps, tanks, or refrigerators attached to the client.

Expected:
A list of devices that are under this account should be shown

![attachfilehandler](https://cloud.githubusercontent.com/assets/12114620/7518295/b9a91276-f4f7-11e4-99c4-62931f61bb21.png)

**Comment by patrickomni** [comment]
Might be a duplicate

**Comment by davroth** [comment]
the devices tab has been removed - suggest closing this bug
