### ISSUE TITLE
Wrong device details name in Samba / Samba User account

### ISSUE THREAD

**Issue by Rahul-Silicon** [patrickomni/omnimobileserver#62]
Wrong Device Details name

Steps to reproduce:
1. Signin without credentials in http://omnistaging.azurewebsites.net/emp 
2. Select Samba / Samba User account to Impersonate. Here in scenario view page device name under latest report  and device details in graph section is showing  different. (In device details side it is listing name as Freeze 2 but in Device label it is shown as Mini Mart #5)

![graph name](https://cloud.githubusercontent.com/assets/12525836/7749270/a593f268-ffe9-11e4-83a8-1b2f73596627.PNG)

**Comment by christopherdude** [comment]
This looks like it was fixed before I got to it?  I don't see the error... I see it correctly showing Mini Mart #5

**Comment by patrickomni** [comment]
Fixed

**Comment by Rahul-Silicon** [comment]
This is fixed in windows based web browser but in iPad if user is changing graph from 24 hours to live data then it is showing pop up that "Data will refresh in every 5 seconds" that time analyse the graph it will show Device name as Freeze 2. 

iPad browser testing Image is attached for reference:

![photo1](https://cloud.githubusercontent.com/assets/12525836/7796897/17eb4ecc-0302-11e5-967e-1791165c1da7.jpg)
