### ISSUE TITLE
No device details and records found

### ISSUE THREAD

**Issue by Rahul-Silicon** [patrickomni/omnimobileserver#63]
Steps to reproduce:
1. Signin without credentials
2. Select  Sempra Energy / Marie Van Zandt account to impersonate as Marie Van Zandt

Here, In Scenario view page, Under stations details it is showing the # 26 numbers of devices but listing only 10 device in first default selection. And when you select the stations from drop down it will show you number of devices available for the selected station with other device details. But in some cases when you select station it is showing devices are available but no records and device details are available for the device.

![graph name](https://cloud.githubusercontent.com/assets/12525836/7750606/d4a6fca4-fff2-11e4-839a-b7f32c6aec5c.PNG)

**Comment by DaveRoth** [comment]
STOP THIS FEED / REMOVE MY EMAIL

Dave Roth

**Comment by patrickomni** [comment]
By design
