### ISSUE TITLE
Let user know that NetTelligence is fetching data after changing display filter

### ISSUE THREAD

**Issue by davroth** [patrickomni/omnimobileserver#64]
Staging server is relatively slow and the screen takes several seconds to refresh w/ new data when display filters are modified. Example:
1. a) Select Sempra/Marie b) observe "Please wait" popup while data is retrieved c) Modify filter from Stations to Station 1 d) wait several seconds for screen to refresh

Suggested solution - use either the "Please wait" popup or the "wheel" icon displayed when changing Device Details display period from Last 3 days to Last 30 days

**Comment by CaseyDengler** [comment]
While the server is quite slow, I am seeing "Please Wait" popups as well as "wheel" icons when changing Device Details. Where exactly are you finding these issues?

**Comment by davroth** [comment]
When I change the list of devices being reported, there is a delay
modifying the data displayed on the left side of the screen (e.g., Data
summaries; latest reports). I don’t see any “popup” or “wheel” letting me
know the system is thinking

I’ve modified comment in bug – sorry it wasn’t clear first time thru (and
thanks for rapid response!) –

dave

_From:_ CaseyDengler [mailto:notifications@github.com]
_Sent:_ Thursday, May 21, 2015 8:49 AM
_To:_ patrickomni/omnimobileserver
_Cc:_ davroth
_Subject:_ Re: [omnimobileserver] Let user know that NetTelligence is
fetching data after changing display filter (#64)

While the server is quite slow, I am seeing "Please Wait" popups as well as
"wheel" icons when changing Device Details. Where exactly are you finding
these issues?

—
Reply to this email directly or view it on GitHub
https://github.com/patrickomni/omnimobileserver/issues/64#issuecomment-104326694
.[image: Image removed by sender.]

**Comment by CaseyDengler** [comment]
Strange, I'm not able to reproduce that.
Whenever I try, I get this Please Wait pop up.
![please wait traps](https://cloud.githubusercontent.com/assets/12438510/7753392/f7889e70-ff99-11e4-9d74-a4884885db64.png)
What web browser, OS, and device are you using?

**Comment by davroth** [comment]
Toshiba Satellite laptop, Windows 8.1, IE 11
I have been having problems w/ my display the past week or so dropping letters, so maybe that's it...

**Comment by CaseyDengler** [comment]
Ah, I'm getting the same issue on IE as well. The circle for the tab spins, but no pop up shows up at all when changing the drop down box on the left. I'll give assign Chris to this as well.

**Comment by DaveRoth** [comment]
STOP THIS FEED / REMOVE MY EMAIL

Dave Roth

**Comment by DaveRoth** [comment]
STOP THIS FEED / REMOVE MY EMAIL

Dave Roth

**Comment by DaveRoth** [comment]
STOP THIS FEED / REMOVE MY EMAIL

Dave Roth

**Comment by DaveRoth** [comment]
STOP THIS FEED / REMOVE MY EMAIL

Dave Roth

**Comment by DaveRoth** [comment]
STOP THIS FEED / REMOVE MY EMAIL

Dave Roth

**Comment by christopherdude** [comment]
Fixed and ready for test

**Comment by CaseyDengler** [comment]
Can't reproduce
