### ISSUE TITLE
Number of Devices for Traps is counting 26 devices when there are only 10

### ISSUE THREAD

**Issue by CaseyDengler** [patrickomni/omnimobileserver#65]
Steps:
1) Log into Omni
2) Go to Traps
3) Observe "# of Devices"
4) Count the number of devices listed below

Expected:
The number of devices should be accurately shown in the # of Devices section

Occurs:
The number of devices is less than half of what the # of Devices is showing.
![trap number of devices](https://cloud.githubusercontent.com/assets/12438510/7753056/e6bc981e-ff97-11e4-9e2a-7478321ac8e0.png)

Note:
Issue #63 shows a similar issue where some areas where there should be no devices, the # of Devices is counting 1 device

**Comment by DaveRoth** [comment]
STOP THIS FEED / REMOVE MY EMAIL

Dave Roth

**Comment by patrickomni** [comment]
There's actually 120

**Comment by patrickomni** [comment]
But, only the 10 have reported so this is by design.
