### ISSUE TITLE
Sempra - trap location icons shown in ocean

### ISSUE THREAD

**Issue by davroth** [patrickomni/omnimobileserver#66]
Could just be bad data but capturing this just in case - the map of trap locations for Sempra show lollipops in blue water surrounding Oahu.

Steps:
1. Browse to http://omnistaging.azurewebsites.net/emp, log in anonymously, and select Sempra / Marie
2. Click ">" on right side of screen to change from Device Data to Map of Devices
3. Observe map that shows up

Expected - lollipops displayed on island of Hawaii

Actual - lollipops displayed in ocean off Oahu

![capture - location](https://cloud.githubusercontent.com/assets/12534533/7753900/3d80dcfa-ff9d-11e4-8493-65d685eaaf04.PNG)

**Comment by CaseyDengler** [comment]
#41 
This is has been logged already, but we don't actually know where they are currently.

Hey Dan, do we have the real coordinates for these devices?

**Comment by DaveRoth** [comment]
STOP THIS FEED / REMOVE MY EMAIL

Dave Roth

**Comment by patrickomni** [comment]
Dan, can we get at least reasonable gps coordinates for the gateways.

**Comment by davroth** [comment]
use 20.7123° N, 156.1548° W, 20.7121° N, 156.1548° W, 20.7122° N, 156.1548° W
 20.7123° N, 156.1547° W, 20.7121° N, 156.1547° W, 20.7122° N, 156.1547° W
 20.7123° N, 156.1549° W, 20.7121° N, 156.1549° W, 20.7122° N, 156.1549° W
 20.7124° N, 156.1549° W, 20.7125° N, 156.1549° W, 20.7126° N, 156.1549° W
 20.7124° N, 156.1547° W, 20.7125° N, 156.1547° W, 20.7126° N, 156.1547° W

**Comment by davroth** [comment]
Still have one lollipop in the ocean...

![capture - lollipop in ocean](https://cloud.githubusercontent.com/assets/12534533/8006917/c2e86b6e-0b4c-11e5-9ae8-2bef776d900d.PNG)

**Comment by davroth** [comment]
fixed
