### ISSUE TITLE
Changing the size of the window while updating the graph will causes the spinning circle to be replaced with the older graph

### ISSUE THREAD

**Issue by CaseyDengler** [patrickomni/omnimobileserver#67]
Steps:
1) Log into Omni
2) Go to Tanks
3) Change the graph from 24h to 3 days
4) While the graph is loading up, make the window smaller (I can't remember what it's called...the button between minimize and close)
5) Observe the graph

Occurs:
The 24 hour graph replaces the spinning circle, making the user believe that the graph went back to the old information rather than trying to update itself. Given enough time (normal loading time), the new 3 day graph will replace the older graph.

3 days is selected but 24 hour graph is shown
![graph window shrink error](https://cloud.githubusercontent.com/assets/12438510/7753933/74649478-ff9d-11e4-9fd4-a83d425587d1.png)

This bug also shows up when making the window large again (just can't remember the name still, between minimize and close) or when snapping the window to the left and right side of the screen.

**Comment by christopherdude** [comment]
Pat, this one may not be worth it.  According to several sources (see http://stackoverflow.com/questions/3444719/ for example) we'd have to implement a POLLING technique to check the location every "n" seconds.  Thoughts?
