### ISSUE TITLE
Fridge rules UI slider can make the ceiling number look like a double negative

### ISSUE THREAD

**Issue by CaseyDengler** [patrickomni/omnimobileserver#68]
Steps:
1) Log into Omni
2) Go to Fridge
3) Go to any rules
4) Change the temperate range to (negative - negative)

Occurs:
Because of the '-' between the two numbers, when the second number on the slider is a negative, the rules almost look like it's saying "between -30 and --10" at a quick glance.

Changing the '-' to a 'to' should work out well.

**Comment by christopherdude** [comment]
Fixed as suggested
