### ISSUE TITLE
On IE, changing the Fridge slider in rules to the lowest possible number forces the rules pop up to close

### ISSUE THREAD

**Issue by CaseyDengler** [patrickomni/omnimobileserver#69]
Steps:
1) Open up IE
2) Log into Omni
3) Go to Fridge
4) Change the rules slider to go to the lowest possible number by quickly sliding the left part of the bar farther than where the bar stops

Occurs:
If the user over shoots the end of the bar, then the rules pop up forcefully closes down.

Note:
If these steps are a bit confusing, please let me know and I'll try to elaborate or just record myself doing it.

**Comment by christopherdude** [comment]
I tried what you said - I couldn't repro.  Which version of IE?

**Comment by CaseyDengler** [comment]
I'm using IE 11. Trying doing it in one swift motion until the mouse is at the edge of the screen perhaps? I'm still getting the error at least.

**Comment by patrickomni** [comment]
No longer repro

**Comment by CaseyDengler** [comment]
Issue is different than originally thought, Closing this one and opening a new one addressing it.
