### ISSUE TITLE
Alerts not showing up on larger table

### ISSUE THREAD

**Issue by CaseyDengler** [patrickomni/omnimobileserver#70]
Steps:
1) Log onto Omni
2) Impersonate any account
3) Find devices that have no errors

Expected:
Devices with no errors show '0's

Occurs:
When there are no alerts, no number is shown. Could seem like the section is broken.

![alerts fridge](https://cloud.githubusercontent.com/assets/12438510/7754844/70aab7fc-ffa4-11e4-85ec-68f46406554c.png)

**Comment by patrickomni** [comment]
Make 0 surface in this milestone.

**Comment by patrickomni** [comment]
Done
