### ISSUE TITLE
Labels inconsistent - "Messages" in summary line; "Latest Reports"

### ISSUE THREAD

**Issue by davroth** [patrickomni/omnimobileserver#75]
I believe these are referring to the same thing (e.g., data packets received off the wire from devices in the current filter). And if they are, then the labels should be the same as many of our users won't recognize these as synonyms.

![capture-labels](https://cloud.githubusercontent.com/assets/12534533/7755301/f03fa9a2-ffa7-11e4-9472-7fc9158660c9.PNG)

**Comment by patrickomni** [comment]
These are all now yours to own and only you can change the defaults.  Have fun :)

**Comment by davroth** [comment]
fixed
