### ISSUE TITLE
Switching from one group to another on the drop down box causes the Device Details page to show up blank on Chrome

### ISSUE THREAD

**Issue by CaseyDengler** [patrickomni/omnimobileserver#76]
Steps:
1) Log into Omni using Chrome
2) Go to Fridge or Tanks
3) Change the sub category on the drop down box (Top left thing)
4) Observe the graph once page has loaded up

Expected:
The graph loads up with the recent data

Occurs:
The graph does not show up and all parts of the Device Details (aside from maps) stays blank
![empty device details](https://cloud.githubusercontent.com/assets/12438510/7756233/f253c5c8-ffae-11e4-836c-33d14b47deaf.png)

**Comment by christopherdude** [comment]
This was an ugly one.  Apparently Chrome understands partial postbacks differently than IE.  I had to run at chromeReloadScript -- Sys.WebForms.PageRequestManager.getInstance().add_endRequest(LoadPage);
