### ISSUE TITLE
Messages not changing to selected devices

### ISSUE THREAD

**Issue by CaseyDengler** [patrickomni/omnimobileserver#78]
Steps:
1) Log into Omni
2) Go to Fridge
3) Change Device Details to Device Data by clicking on the arrow on the right below Device Details
4) Deselect all devices

Expected:
Messages disappear as any devices related to them are no longer selected

Occurs:
Messages stay up regardless of what devices are selected

![message still there](https://cloud.githubusercontent.com/assets/12438510/7756456/326bda6e-ffb0-11e4-8263-69f5b2719b0f.png)

**Comment by patrickomni** [comment]
sproc already expects days

**Comment by davroth** [comment]
Is this still a problem?

**Comment by davroth** [comment]
I think we can move this to V2 where it needs to be fixed to help customers who have large numbers of devices (thinking Eastside w/ 300 traps where they may want to filter by location or ??

For this release, we doc this as a feature - the Alert box, which has been moved off the carousel, shows all active alerts...

**Comment by davroth** [comment]
no repro
