### ISSUE TITLE
When changing drop box on the top left of any impersonation, the titles on the tables cannot be changed (Chrome only)

### ISSUE THREAD

**Issue by CaseyDengler** [patrickomni/omnimobileserver#80]
Steps:
1) Log into Omni using Chrome
2) Go to Traps, Tanks, or Fridge
3) Change the drop box on the top left
4) Attempt to change the labels on the tables

Expected:
User is able to change the labels on the tables after switching

Occurs:
The user is unable to change any labels. No small pop up saying that they can shows up and the double clicking any labels only highlights them

Note: Related to issue #76 as both are Chrome only issues so far

**Comment by patrickomni** [comment]
If it's a hard fix, punt

**Comment by davroth** [comment]
Still an issue?

**Comment by patrickomni** [comment]
Nope.

**Comment by davroth** [comment]
No repro Chrome v43, Windows 8.1, but there is a new error
