### ISSUE TITLE
Time selection control missing from Device Data carousel view

### ISSUE THREAD

**Issue by davroth** [patrickomni/omnimobileserver#84]
I am able to set time span for the Device Details graph on the carousel view. However, that control is not visible on Windows 8.1, IE 11 when carousel is moved to Device Data view.

![capture - time control missing](https://cloud.githubusercontent.com/assets/12534533/7759808/7f328be0-ffc9-11e4-8ef2-15515588c353.PNG)

**Comment by christopherdude** [comment]
I don't know what this one means.

**Comment by davroth** [comment]
A number of alerts may be displayed in the Device Data pane. Is there a way to direct NetTel how far back to go? 

There is a drop down on Device Details carousel graph that allows user to specify last  24 hrs, last 3 days, etc.

Do we want similar on Device Data?

I'm assuming we want to be able to view alert history

-----Original Message-----

**Comment by patrickomni** [comment]
We're going to move this out of the carosusel

**Comment by patrickomni** [comment]
Alerts are not part of carousel anymore
