### ISSUE TITLE
Missing some labels on the data tables

### ISSUE THREAD

**Issue by CaseyDengler** [patrickomni/omnimobileserver#85]
Steps:
1) Log into Omni
2) Go to Traps, Tanks, or Fridge
3) Look at "Boo" on the left side

Labels are either missing or named oddly. Should be set back to defaults.
![odd and missing labels](https://cloud.githubusercontent.com/assets/12438510/7763829/d4b1ef84-fffb-11e4-90fc-7e030351d45c.png)

**Comment by patrickomni** [comment]
Fixed in next build

**Comment by CaseyDengler** [comment]
Some are still miss named
![names](https://cloud.githubusercontent.com/assets/12438510/7764622/d4634372-0008-11e5-8bfa-c77bfae976ab.png)

![names 2](https://cloud.githubusercontent.com/assets/12438510/7764638/0bb88418-0009-11e5-8d61-f15a5271128b.png)

**Comment by patrickomni** [comment]
Dave owns these.

**Comment by davroth** [comment]
fixed
