### ISSUE TITLE
Blank Account

### ISSUE THREAD

**Issue by patrickomni** [patrickomni/omnimobileserver#9]
Steps to reproduce:
1. Login to omnim2m.net
2. Add Account
3. Do not enter any account name and account type for the user and hit save button.
4. It will create new account with blank account name.

![blank](https://cloud.githubusercontent.com/assets/12114620/7518969/e304e434-f4fb-11e4-90b4-fd7c10fe88b4.PNG)

**Comment by christopherdude** [comment]
Wow, you are getting really good at this!  GREAT find!  Fixed.

**Comment by CaseyDengler** [comment]
Keep trying to cheat the system to reproduce, but can't.
